#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['warden','new','aj.warden','aj.warden.root']}
execute as @e[type=minecraft:marker,tag=aj.warden.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function warden:summon/zzz/execute/2
function warden:assert_animation_flags