#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.warden.bone.body] ^0 ^-0.5 ^0
tp @s[tag=aj.warden.bone.right_ribcage] ^-0.437 ^-0.375 ^0.25
tp @s[tag=aj.warden.bone.left_ribcage] ^0.438 ^-0.375 ^0.25
tp @s[tag=aj.warden.bone.head] ^0 ^0.312 ^0
tp @s[tag=aj.warden.bone.right_tendril] ^-0.5 ^1.062 ^0
tp @s[tag=aj.warden.bone.left_tendril] ^0.5 ^1.062 ^0
tp @s[tag=aj.warden.bone.right_arm] ^-0.812 ^0.312 ^-0.062
tp @s[tag=aj.warden.bone.left_arm] ^0.813 ^0.312 ^-0.062
tp @s[tag=aj.warden.bone.right_leg] ^-0.369 ^-1 ^0
tp @s[tag=aj.warden.bone.left_leg] ^0.369 ^-1 ^0
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2