#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.warden.bone.body] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.right_ribcage] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.left_ribcage] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.right_tendril] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.left_tendril] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.right_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.left_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.right_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.warden.bone.left_leg] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~