#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.warden.anim.animation.warden.sniff
execute if score .aj.anim_loop aj.warden.animating matches 0 run function warden:animation_loop
scoreboard players set #execute aj.i 1