#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0 ^-2.516 ^0 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0 ^-2.508 ^0 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0 ^-2.489 ^0 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0 ^-2.456 ^0 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0 ^-2.415 ^0 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0 ^-2.362 ^0 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0 ^-2.294 ^0 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0 ^-2.208 ^0 ~ ~