#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0 ^-0.82 ^0.209 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0 ^-0.782 ^0.221 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0 ^-0.743 ^0.233 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0 ^-0.71 ^0.243 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0 ^-0.688 ^0.25 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0 ^-0.683 ^0.252 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0 ^-0.68 ^0.255 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0 ^-0.679 ^0.257 ~ ~