#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0 ^-0.697 ^0.269 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0 ^-0.697 ^0.266 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0 ^-0.696 ^0.262 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0 ^-0.693 ^0.257 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0 ^-0.688 ^0.25 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0 ^-0.681 ^0.241 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0 ^-0.673 ^0.23 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0 ^-0.663 ^0.217 ~ ~