#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [75.4492f,0f,2.7344f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [74.6536f,0f,2.6904f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [73.5034f,0f,2.6367f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [71.9638f,0f,2.5732f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [70f,0f,2.5f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [67.5594f,0f,2.4128f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [64.4633f,0f,2.3023f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [60.8004f,0f,2.1714f]