#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-4.183 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-4.116 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-4.037 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-3.954 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-3.864 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-3.758 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-3.641 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-3.515 ^0 ~ ~