#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0 ^-1.301 ^-0.012 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0 ^-1.378 ^-0.012 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0 ^-1.364 ^0.006 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0 ^-1.316 ^0.027 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0 ^-1.246 ^0.056 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0 ^-1.163 ^0.087 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0 ^-1.074 ^0.12 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0 ^-0.99 ^0.149 ~ ~