#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^0 ^-0.652 ^0.202 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^0 ^-0.64 ^0.186 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0 ^-0.627 ^0.169 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0 ^-0.614 ^0.151 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0 ^-0.6 ^0.132 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0 ^-0.586 ^0.114 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0 ^-0.572 ^0.095 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0 ^-0.559 ^0.078 ~ ~