#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.107 ^-1.663 ^0.054 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.084 ^-1.599 ^0.062 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.055 ^-1.562 ^0.061 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.024 ^-1.55 ^0.056 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.007 ^-1.552 ^0.059 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.038 ^-1.565 ^0.068 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.069 ^-1.585 ^0.081 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.097 ^-1.606 ^0.095 ~ ~