#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^0.016 ^-0.199 ^0.85 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^0.016 ^-0.138 ^0.799 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0.016 ^-0.075 ^0.74 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0.016 ^-0.014 ^0.675 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0.015 ^0.045 ^0.603 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0.014 ^0.1 ^0.527 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0.012 ^0.149 ^0.448 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0.01 ^0.192 ^0.368 ~ ~