#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.093 ^-0.639 ^0.289 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.099 ^-0.671 ^0.254 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.089 ^-0.662 ^0.274 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.077 ^-0.627 ^0.32 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.062 ^-0.573 ^0.387 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.046 ^-0.513 ^0.464 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.03 ^-0.452 ^0.541 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.016 ^-0.397 ^0.611 ~ ~