#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.043 ^-1.557 ^0.113 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.03 ^-1.505 ^0.119 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.018 ^-1.445 ^0.125 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.005 ^-1.378 ^0.13 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.007 ^-1.308 ^0.136 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.019 ^-1.235 ^0.143 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.029 ^-1.162 ^0.149 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.04 ^-1.09 ^0.155 ~ ~