#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.485 ^-4.138 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.502 ^-4.146 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.509 ^-4.107 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.507 ^-4.02 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.492 ^-3.867 ^-0.001 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.466 ^-3.655 ^-0.002 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.431 ^-3.404 ^-0.003 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.387 ^-3.13 ^-0.004 ~ ~