#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-68.0831f,0f,20.2902f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-67.6025f,0f,24.0191f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-67.8516f,0f,23.1807f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-68.2178f,0f,7.6855f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-59.0625f,0f,3.75f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-53.3838f,0f,5.0342f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-67.6172f,0f,5.3516f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-66.6915f,0f,4.8645f]