#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [13.2031f,0f,0f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [9.3567f,0f,0f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [5.8105f,0f,0f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [2.3865f,0f,0f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [-0.2747f,0f,0f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [-0.4785f,0f,0f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [-0.6189f,0f,0f]