#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.36 ^-1.38 ^-0.663 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.367 ^-1.222 ^-0.621 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.39 ^-1.03 ^-0.515 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.436 ^-1.057 ^-0.542 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.497 ^-1.248 ^-0.634 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.551 ^-1.317 ^-0.631 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.603 ^-1.393 ^-0.619 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.65 ^-1.47 ^-0.603 ~ ~