#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.466 ^-0.937 ^1.622 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.468 ^-0.889 ^1.646 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.471 ^-0.829 ^1.667 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.474 ^-0.755 ^1.683 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.479 ^-0.667 ^1.693 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.483 ^-0.563 ^1.694 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.489 ^-0.439 ^1.683 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.494 ^-0.298 ^1.655 ~ ~