#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.5 ^-0.894 ^1.297 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.496 ^-0.938 ^1.309 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.49 ^-0.977 ^1.321 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.484 ^-1.005 ^1.335 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.478 ^-1.019 ^1.357 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.476 ^-1.021 ^1.371 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.474 ^-1.025 ^1.386 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.472 ^-1.03 ^1.404 ~ ~