#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-66.399f,-6.9372f,-4.4095f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-147.338f,-15.3935f,-10.0728f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-172.0868f,-17.9807f,-13.7047f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-177.1065f,-18.5127f,-16.9166f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-179.3592f,-18.76f,-20.2511f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-179.4385f,-18.7817f,-23.4974f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-177.9376f,-18.6373f,-26.4447f]