#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [21.0293f,0f,-5.1465f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [22.4219f,0f,-6.0303f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [23.6853f,0f,-6.7869f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [24.7976f,0f,-7.3972f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [29.0234f,0f,-8.7305f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [32.8168f,0f,-8.4421f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [34.8096f,0f,-7.6196f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [33.8986f,0f,-7.6071f]