#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.652 ^-0.558 ^0.129 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.638 ^-0.491 ^0.167 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.627 ^-0.433 ^0.199 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.618 ^-0.386 ^0.223 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.6 ^-0.288 ^0.277 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.605 ^-0.233 ^0.286 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.617 ^-0.206 ^0.269 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.612 ^-0.193 ^0.233 ~ ~