#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.55 ^-2.461 ^-0.062 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.541 ^-2.26 ^-0.062 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.543 ^-2.097 ^-0.062 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.552 ^-1.97 ^-0.062 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.562 ^-1.868 ^-0.062 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.57 ^-1.786 ^-0.062 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.575 ^-1.719 ^-0.062 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.577 ^-1.66 ^-0.062 ~ ~