#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-75.1038f,-3.3927f,-11.1236f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-72.1754f,-3.1999f,-11.1305f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-68.8582f,-3.2228f,-10.8826f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-65.2476f,-3.4568f,-10.4437f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-61.4423f,-3.8868f,-9.8747f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-57.5427f,-4.4861f,-9.2319f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-53.6498f,-5.2169f,-8.5661f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [-49.8632f,-6.0301f,-7.9213f]