#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-46.2804f,-6.8674f,-7.3341f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [-42.9964f,-7.6628f,-6.8347f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [-40.1038f,-8.3443f,-6.447f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [-37.6931f,-8.8369f,-6.191f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [-31.1162f,-9.2689f,-6.3908f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [-26.492f,-8.2822f,-6.1192f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [-24.2049f,-6.5651f,-5.6366f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [-24.0977f,-4.8425f,-5.7666f]