#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.11 ^-1.016 ^0.483 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.109 ^-1.014 ^0.508 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0.11 ^-1.013 ^0.529 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0.111 ^-1.01 ^0.546 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0.113 ^-1.007 ^0.558 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0.116 ^-1.003 ^0.563 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0.128 ^-0.989 ^0.547 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0.165 ^-0.941 ^0.446 ~ ~