#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.427 ^-0.928 ^0.453 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.427 ^-0.925 ^0.453 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.428 ^-0.92 ^0.453 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.428 ^-0.911 ^0.453 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.429 ^-0.899 ^0.453 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.429 ^-0.883 ^0.452 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.43 ^-0.862 ^0.451 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.431 ^-0.837 ^0.448 ~ ~