#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.74 ^-0.303 ^0.992 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.744 ^-0.301 ^0.986 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.749 ^-0.294 ^0.976 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.754 ^-0.281 ^0.962 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.759 ^-0.261 ^0.943 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.765 ^-0.233 ^0.918 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.77 ^-0.196 ^0.884 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.776 ^-0.153 ^0.843 ~ ~