#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [-0.7031f,0f,0f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [-0.7385f,0f,0f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [-0.7324f,0f,0f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [-0.6921f,0f,0f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [-0.625f,0f,0f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [-0.5383f,0f,0f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [-0.4395f,0f,0f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [-0.3357f,0f,0f]