#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,0f,-19.4071f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0f,0f,-21.185f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,-22.2854f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0f,0f,-22.5964f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0f,0f,-22.4679f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0f,0f,-22.0143f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0f,0f,-21.2772f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0f,0f,-20.2984f]