#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [17.8635f,-3.9474f,-1.0837f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [15.7125f,-3.927f,-1.3074f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [12.4434f,-3.9566f,-1.5334f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [8.3216f,-4.0345f,-1.7425f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [3.6126f,-4.1574f,-1.9152f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [-1.4366f,-4.3204f,-2.034f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-6.7051f,-4.5238f,-2.0771f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-11.8056f,-4.7405f,-2.0313f]