#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.453 ^-2.459 ^0.249 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.454 ^-2.463 ^0.248 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.454 ^-2.468 ^0.248 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.454 ^-2.473 ^0.247 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.455 ^-2.476 ^0.246 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.455 ^-2.478 ^0.246 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.455 ^-2.479 ^0.246 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.455 ^-2.476 ^0.246 ~ ~