#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [127.543f,2.6778f,2.0388f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [123.8851f,2.5597f,1.9875f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [119.8221f,2.4252f,1.9181f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [115.333f,2.2756f,1.8318f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [110.397f,2.1123f,1.7308f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [104.9753f,1.9361f,1.6129f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [98.903f,1.7467f,1.4675f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [92.2827f,1.5473f,1.3065f]