#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.387 ^-2.672 ^-0.032 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.386 ^-2.591 ^-0.03 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.381 ^-2.5 ^-0.021 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.371 ^-2.397 ^-0.004 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.356 ^-2.276 ^0.023 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.334 ^-2.125 ^0.063 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.307 ^-1.953 ^0.113 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.276 ^-1.768 ^0.168 ~ ~