#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-90f,-17.5f,-2.5f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-90.0184f,-17.5066f,-2.4855f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-90.2063f,-17.5737f,-2.3381f]