#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [11.9072f,0f,0.8727f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [13.943f,0f,0.6624f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [15.8222f,0f,0.4508f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [17.4612f,0f,0.2587f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [18.7767f,0f,0.1069f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [19.6851f,0f,0.0163f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [20.1855f,0f,0f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [17.7014f,0f,0f]