#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.427 ^-0.903 ^0.452 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.427 ^-0.907 ^0.452 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.427 ^-0.912 ^0.452 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.427 ^-0.916 ^0.452 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.427 ^-0.921 ^0.452 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.427 ^-0.925 ^0.452 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.427 ^-0.927 ^0.452 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.427 ^-0.929 ^0.453 ~ ~