#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.5 ^-2.875 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.431 ^-2.89 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.34 ^-2.926 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.235 ^-2.98 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.126 ^-3.047 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.022 ^-3.119 ^-0.001 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.072 ^-3.188 ^-0.001 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.154 ^-3.244 ^-0.001 ~ ~