#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [73.2227f,0f,2.7344f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [74.0115f,0f,2.7686f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [74.7241f,0f,2.793f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [75.3256f,0f,2.8076f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [75.7812f,0f,2.8125f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [76.0562f,0f,2.8076f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [76.1157f,0f,2.793f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [75.925f,0f,2.7686f]