#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.337 ^-1.095 ^-0.004 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.339 ^-1.085 ^0.057 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.342 ^-1.072 ^0.124 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.346 ^-1.05 ^0.193 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.352 ^-1.027 ^0.266 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.362 ^-1.001 ^0.342 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.373 ^-0.968 ^0.419 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.386 ^-0.926 ^0.495 ~ ~