#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.852 ^-3.424 ^-0.31 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.814 ^-3.397 ^-0.367 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.782 ^-3.368 ^-0.424 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.757 ^-3.337 ^-0.477 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.741 ^-3.303 ^-0.525 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.732 ^-3.263 ^-0.566 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.73 ^-3.217 ^-0.597 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.734 ^-3.164 ^-0.618 ~ ~