#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.676 ^-0.07 ^0.995 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.693 ^-0.047 ^1.024 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.711 ^-0.027 ^1.05 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.728 ^-0.015 ^1.071 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.742 ^-0.019 ^1.083 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.744 ^-0.026 ^1.09 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.747 ^-0.037 ^1.097 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.749 ^-0.052 ^1.105 ~ ~