#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-1.233 ^-2.786 ^0.068 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-1.184 ^-2.576 ^0.058 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-1.138 ^-2.363 ^0.028 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-1.095 ^-2.134 ^-0.061 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-1.019 ^-1.872 ^-0.237 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.89 ^-1.664 ^-0.427 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.754 ^-1.561 ^-0.57 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.67 ^-1.526 ^-0.639 ~ ~