#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [10.4119f,-0.1707f,-19.9192f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [7.6869f,-0.126f,-21.563f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [2.7114f,-0.0444f,-22.4187f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-3.7705f,0.0529f,-22.3934f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-11.7204f,0.1338f,-21.7764f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-21.4656f,0.2108f,-20.68f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-32.6752f,0.2897f,-19.1846f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-45.0182f,0.3765f,-17.3708f]