#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^-0.437 ^-0.495 ^0.336 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^-0.437 ^-0.462 ^0.316 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^-0.437 ^-0.434 ^0.296 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^-0.437 ^-0.409 ^0.277 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^-0.437 ^-0.388 ^0.261 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^-0.437 ^-0.375 ^0.25 ~ ~