#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^-2.875 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.568 ^-2.912 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.659 ^-2.976 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.762 ^-3.063 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.867 ^-3.166 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.965 ^-3.278 ^-0.001 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-1.052 ^-3.389 ^-0.001 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-1.123 ^-3.488 ^-0.001 ~ ~