#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.416 ^-2.298 ^0.25 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.411 ^-2.303 ^0.25 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.406 ^-2.294 ^0.25 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.406 ^-2.295 ^0.25 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.409 ^-2.301 ^0.25 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.409 ^-2.301 ^0.25 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.409 ^-2.301 ^0.25 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.409 ^-2.301 ^0.25 ~ ~