#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.369 ^-1 ^0 ~ ~