#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [37.2553f,-0.1285f,5.1172f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [43.4558f,-0.3671f,5.172f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [49.6128f,-0.6784f,5.1772f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [55.669f,-1.0593f,5.1359f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [61.5678f,-1.5028f,5.0518f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [67.2533f,-1.9986f,4.93f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [72.6707f,-2.5332f,4.7769f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [77.7665f,-3.0905f,4.6007f]