#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.454 ^-0.646 ^1.39 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.459 ^-0.644 ^1.406 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.467 ^-0.6 ^1.396 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.476 ^-0.575 ^1.362 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.483 ^-0.615 ^1.337 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.489 ^-0.697 ^1.315 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.493 ^-0.773 ^1.31 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.496 ^-0.823 ^1.307 ~ ~