#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.752 ^-0.068 ^1.113 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.754 ^-0.087 ^1.119 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.757 ^-0.106 ^1.125 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.759 ^-0.125 ^1.128 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.762 ^-0.142 ^1.13 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.764 ^-0.158 ^1.129 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.766 ^-0.171 ^1.126 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.768 ^-0.181 ^1.119 ~ ~