#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0.6372f,-0.0104f,-1.4678f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [2.2776f,-0.0373f,-3.5876f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [4.5145f,-0.074f,-6.1795f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [6.9413f,-0.1138f,-9.0635f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [9.1511f,-0.15f,-12.0595f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [10.7373f,-0.176f,-14.9874f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [11.2931f,-0.1851f,-17.6673f]