#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [24.9244f,0.1144f,0.2295f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [18.4521f,0.0606f,0.172f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [12.5577f,0.0267f,0.1204f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [7.3437f,0.0086f,0.0734f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [2.9125f,0.0012f,0.0307f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [0f,0f,0f]