#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [82.4877f,-3.6526f,4.4114f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [86.7825f,-4.1996f,4.2205f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [90.5995f,-4.711f,4.041f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [93.8879f,-5.1659f,3.8872f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [102.8336f,-6.5891f,3.2856f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [108.1409f,-7.6213f,3.5335f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [108.8587f,-7.8856f,3.8712f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [105.5097f,-7.3654f,3.4843f]