#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,0f,-19.1197f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,0f,-17.7827f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,0f,-16.3293f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,0f,-14.8011f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,-13.2399f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [0f,0f,-11.6874f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [0f,0f,-10.1855f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0f,0f,-8.7758f]