#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.369 ^-1.118 ^0.161 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.369 ^-1.062 ^0.448 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.369 ^-1.019 ^0.509 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.369 ^-1.003 ^0.249 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.369 ^-0.999 ^-0.025 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.369 ^-0.998 ^-0.037 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.369 ^-0.998 ^-0.039 ~ ~