#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.454 ^-3.409 ^0.25 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.455 ^-3.265 ^0.25 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.455 ^-3.12 ^0.25 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.455 ^-2.978 ^0.25 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.454 ^-2.843 ^0.25 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.454 ^-2.717 ^0.25 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.453 ^-2.605 ^0.25 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.451 ^-2.509 ^0.25 ~ ~