#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-78.6623f,5.1368f,6.6073f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-73.9252f,2.6362f,10.4387f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-71.1684f,2.7614f,16.2135f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-68.293f,3.4315f,19.2345f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-65.0552f,2.9135f,17.387f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-61.7956f,2.3806f,14.5483f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-58.2692f,1.9714f,11.0237f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [-54.657f,1.7389f,7.1207f]