#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.45 ^-2.434 ^0.25 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.448 ^-2.357 ^0.25 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.445 ^-2.306 ^0.25 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.441 ^-2.277 ^0.25 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.436 ^-2.265 ^0.25 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.431 ^-2.266 ^0.25 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.426 ^-2.275 ^0.25 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.421 ^-2.287 ^0.25 ~ ~