#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.447 ^-0.886 ^0.453 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.447 ^-0.884 ^0.453 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.446 ^-0.88 ^0.453 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.446 ^-0.872 ^0.453 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.445 ^-0.861 ^0.453 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.445 ^-0.846 ^0.452 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.444 ^-0.827 ^0.451 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.443 ^-0.804 ^0.448 ~ ~