#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.401 ^-0.918 ^0.569 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.415 ^-0.918 ^0.638 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.43 ^-0.916 ^0.702 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.444 ^-0.913 ^0.759 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.456 ^-0.91 ^0.809 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.468 ^-0.905 ^0.851 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.477 ^-0.9 ^0.886 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.485 ^-0.894 ^0.914 ~ ~