#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [136.4291f,-0.4766f,1.1946f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [140.7775f,0.3602f,1.1365f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [144.4684f,1.1508f,1.255f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [146.9033f,1.8341f,1.4628f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [147.4825f,2.3491f,1.6445f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [147.0469f,2.5238f,1.6911f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [146.4586f,2.669f,1.7459f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [145.6965f,2.7854f,1.8057f]