#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [-4.0741f,0f,0f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [-3.9956f,0f,0f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [-3.7446f,0f,0f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [-3.2978f,0f,0f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [-2.6318f,0f,0f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [-1.7234f,0f,0f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [-0.5493f,0f,0f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [8.4796f,0f,0f]