#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-0.0505f,0f,-16.6502f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-0.0373f,0f,-19.1496f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-0.0132f,0f,-21.5674f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0.2112f,0f,-24.5329f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [1.2043f,0f,-29.2118f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [2.6447f,0f,-34.938f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [4.124f,0f,-41.058f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [5.2335f,0f,-46.9184f]