#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.369 ^-3.884 ^0 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.369 ^-3.75 ^0 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.369 ^-3.617 ^0 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.369 ^-3.487 ^0 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.369 ^-3.364 ^0 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.369 ^-3.251 ^0 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.369 ^-3.151 ^0 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.369 ^-3.066 ^0 ~ ~