#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.43 ^-2.026 ^0.265 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.433 ^-1.983 ^0.267 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.435 ^-1.932 ^0.27 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.437 ^-1.876 ^0.272 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.438 ^-1.817 ^0.273 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.439 ^-1.755 ^0.275 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.439 ^-1.692 ^0.276 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.439 ^-1.631 ^0.277 ~ ~