#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [-4.4129f,1.0288f,2.1415f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [-2.9381f,0.7361f,2.2519f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [-1.3101f,0.478f,2.343f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [0.4947f,0.2443f,2.4217f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [2.5f,0f,2.5f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [3.7809f,-0.1669f,2.5335f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [5.7041f,-0.363f,2.599f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [8.1088f,-0.584f,2.6875f]