#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.442 ^-0.777 ^0.444 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.441 ^-0.746 ^0.438 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.44 ^-0.713 ^0.43 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.439 ^-0.678 ^0.42 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.439 ^-0.641 ^0.407 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.438 ^-0.603 ^0.392 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.437 ^-0.566 ^0.375 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.437 ^-0.529 ^0.356 ~ ~