#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-1.2519f,0f,10.8763f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-0.5641f,0f,10.3948f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0.3006f,0f,9.7878f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [1.1899f,0f,9.1467f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [2.2582f,0f,8.3631f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [3.4835f,0f,7.4562f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [4.8437f,0f,6.4453f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [6.317f,0f,5.3497f]