#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-152.5f,2.5f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-161.1604f,3.2768f,0.9405f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-168.4085f,4.2655f,1.4689f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-174.2697f,5.4068f,1.6617f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-178.7695f,6.6413f,1.5951f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [178.0666f,7.9098f,1.3453f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [176.2134f,9.1528f,0.9888f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [175.6452f,10.3111f,0.6017f]