#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [10.8342f,-0.8254f,2.7905f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [13.7196f,-1.0819f,2.9007f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [16.6044f,-1.3478f,3.0115f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [19.328f,-1.6164f,3.1174f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [21.73f,-1.8807f,3.214f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [23.6501f,-2.1332f,3.2976f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [24.9281f,-2.366f,3.3649f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [25.404f,-2.5713f,3.4133f]