#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.438 ^-1.573 ^0.278 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.437 ^-1.519 ^0.279 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.436 ^-1.471 ^0.279 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.435 ^-1.432 ^0.279 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.431 ^-1.354 ^0.279 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.428 ^-1.305 ^0.278 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.428 ^-1.287 ^0.277 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.429 ^-1.303 ^0.275 ~ ~