#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,0f,-1.4364f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,0f,-3.4756f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,0f,-5.9575f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,0f,-8.7221f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,0f,-11.6094f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0f,0f,-14.4593f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,0f,-17.1119f]