#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.656 ^-0.125 ^0.887 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.641 ^-0.107 ^0.941 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.638 ^-0.122 ^0.864 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.645 ^-0.154 ^0.749 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.642 ^-0.15 ^0.782 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.639 ^-0.127 ^0.878 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.649 ^-0.107 ^0.939 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.661 ^-0.091 ^0.967 ~ ~