#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [-9.4963f,-0.5395f,2.3768f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [-7.0118f,-0.295f,1.7787f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [-4.6027f,-0.1335f,1.2023f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [-2.4736f,-0.0434f,0.6838f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [-0.829f,-0.0062f,0.2564f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [0f,0f,0f]