#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.5 ^-0.873 ^1.305 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.504 ^-0.918 ^1.302 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.51 ^-0.955 ^1.3 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.515 ^-0.98 ^1.303 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.52 ^-0.99 ^1.316 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.522 ^-0.992 ^1.326 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.524 ^-0.994 ^1.34 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.526 ^-0.998 ^1.356 ~ ~