#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [-38.8426f,2.2797f,-7.1629f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [-42.761f,2.2745f,-6.9727f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [-41.591f,2.2568f,-6.1823f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [-37.9019f,2.214f,-5.2392f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [-32.6611f,2.1444f,-3.9924f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [-26.5524f,2.0524f,-2.5824f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [-20.2593f,1.9459f,-1.1487f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [-14.465f,1.8372f,0.1724f]