#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^-0.801 ^0.284 ^0.216 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^-0.804 ^0.297 ^0.142 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^-0.806 ^0.306 ^0.075 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^-0.809 ^0.31 ^0.016 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^-0.811 ^0.312 ^-0.032 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~