#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..133 run function warden:animations/animation.warden.emerge/tree/right_tendril_display_0-133