#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function warden:animations/animation.warden.emerge/tree/root_bone_name
execute if entity @s[type=minecraft:armor_stand] run function warden:animations/animation.warden.emerge/tree/display_bone_name