#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0.3557f,28.2174f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0.6607f,27.0775f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [1.0287f,25.8677f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [1.4521f,24.595f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [1.9237f,23.2663f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [2.4361f,21.8883f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [2.9819f,20.4681f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [3.5537f,19.0125f,0f]