#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [11.1111f,-12.4074f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [11.2153f,-15.7154f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [11.25f,-18.9062f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [11.2153f,-21.8801f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [11.1111f,-24.537f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [10.9375f,-26.7773f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [10.6944f,-28.5012f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [10.3819f,-29.6087f,0f]