#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.sniff/tree/head_display_0-63
execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [2.5269f,-10.5557f,-0.1445f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [1.1891f,-5.2273f,-0.036f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [0.2386f,-1.1742f,-0.0019f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0f,0f,0f]