#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [1.0995f,3.5952f,0.0324f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [2.7568f,8.3788f,0.1832f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [4.877f,14.1075f,0.5385f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [7.4003f,20.5308f,1.1896f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [10.3045f,27.3917f,2.2352f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [13.6021f,34.4282f,3.7866f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [17.3315f,41.3774f,5.9688f]