#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [21.5368f,47.9804f,8.9082f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [26.218f,53.9937f,12.6903f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [31.2303f,59.2074f,17.2615f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [36.1152f,63.4761f,22.26f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [40.1429f,67.3342f,27.1606f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [41.6582f,70.8153f,30.5452f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [40.6929f,74.3303f,32.9551f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [34.2038f,77.4696f,32.7224f]