#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.085 ^0.286 ^0.185 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.104 ^0.28 ^0.198 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.12 ^0.276 ^0.206 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.13 ^0.274 ^0.207 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.133 ^0.276 ^0.198 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.125 ^0.283 ^0.176 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.107 ^0.292 ^0.146 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.083 ^0.3 ^0.112 ~ ~