#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.056 ^0.306 ^0.076 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.031 ^0.31 ^0.044 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.012 ^0.312 ^0.017 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.001 ^0.312 ^0.001 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.001 ^0.312 ^-0.001 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.001 ^0.312 ^-0.001 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^0.312 ^0 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.001 ^0.312 ^0.002 ~ ~