#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.034 ^0.297 ^0.153 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.043 ^0.296 ^0.152 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.051 ^0.296 ^0.15 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.059 ^0.296 ^0.147 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.065 ^0.297 ^0.142 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.069 ^0.297 ^0.138 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.072 ^0.298 ^0.133 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.072 ^0.299 ^0.127 ~ ~