#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.152 ^0.955 ^0.741 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.069 ^0.931 ^0.798 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.004 ^0.912 ^0.834 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.06 ^0.9 ^0.851 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.097 ^0.902 ^0.845 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.104 ^0.921 ^0.812 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.079 ^0.951 ^0.76 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.002 ^0.986 ^0.691 ~ ~