#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.sniff/tree/left_arm_display_0-63
execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [5.0536f,-6.1038f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [2.5099f,-2.9967f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [0.5699f,-0.6631f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0f,0f,0f]