#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.41 ^-0.415 ^0.306 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.418 ^-0.417 ^0.297 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.425 ^-0.418 ^0.287 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.431 ^-0.42 ^0.277 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.438 ^-0.421 ^0.268 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.45 ^-0.423 ^0.247 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.463 ^-0.424 ^0.223 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.475 ^-0.425 ^0.197 ~ ~