#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.429 ^-0.38 ^0.266 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.417 ^-0.387 ^0.287 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.401 ^-0.395 ^0.312 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.382 ^-0.404 ^0.338 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.36 ^-0.414 ^0.364 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.335 ^-0.424 ^0.389 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.309 ^-0.434 ^0.412 ~ ~