#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.sniff/tree/left_ribcage_root_0-63
execute if score .this aj.frame matches 64 run tp @s ^0.462 ^-0.384 ^0.206 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.45 ^-0.38 ^0.229 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.44 ^-0.376 ^0.245 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~