#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.635 ^0.314 ^0.508 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.665 ^0.314 ^0.468 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.693 ^0.313 ^0.427 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.715 ^0.312 ^0.39 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.723 ^0.312 ^0.376 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.728 ^0.312 ^0.365 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.734 ^0.312 ^0.355 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.738 ^0.312 ^0.344 ~ ~