#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.814 ^0.309 ^-0.082 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.808 ^0.309 ^-0.127 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.8 ^0.309 ^-0.171 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.79 ^0.309 ^-0.213 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.779 ^0.309 ^-0.251 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.767 ^0.309 ^-0.283 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.757 ^0.309 ^-0.309 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.748 ^0.31 ^-0.328 ~ ~