#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [7.8351f,24.6356f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [8.2209f,27.6734f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [8.1647f,30.2393f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [7.5735f,32.1945f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [6.1307f,33.9625f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [3.5407f,35.3336f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0.1716f,36.1969f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-3.5912f,36.5523f,0f]