#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.372 ^1.08 ^-0.213 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.426 ^1.074 ^-0.177 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.455 ^1.068 ^-0.153 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.469 ^1.066 ^-0.136 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.479 ^1.064 ^-0.116 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.487 ^1.063 ^-0.095 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.493 ^1.062 ^-0.073 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.496 ^1.062 ^-0.052 ~ ~