#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [7.3527f,-51.9777f,-6.1795f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [10.9405f,-50.0959f,-5.2593f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [11.6018f,-46.6816f,-4.1321f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [10.6652f,-42.181f,-3.0604f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [9.253f,-36.5401f,-2.0912f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [7.5949f,-30.1539f,-1.3147f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [5.8441f,-23.4243f,-0.7472f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [4.118f,-16.7563f,-0.3686f]