#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [1.0416f,1.8164f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [2.5291f,4.2713f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [4.3504f,7.2258f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [6.3935f,10.5412f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [8.5462f,14.0787f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [10.6963f,17.6994f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [12.7319f,21.2646f,0f]