#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.498 ^1.061 ^0.06 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.489 ^1.059 ^0.144 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.469 ^1.053 ^0.245 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.433 ^1.042 ^0.355 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.381 ^1.025 ^0.466 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.314 ^1.005 ^0.572 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.236 ^0.98 ^0.665 ~ ~