#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.467 ^1.032 ^0.348 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.481 ^1.037 ^0.305 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.49 ^1.043 ^0.258 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.492 ^1.05 ^0.209 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.488 ^1.057 ^0.162 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.483 ^1.063 ^0.11 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.469 ^1.071 ^0.053 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.436 ^1.08 ^-0.024 ~ ~