#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.321 ^1.061 ^0.388 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.338 ^1.06 ^0.377 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.39 ^1.057 ^0.33 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.463 ^1.043 ^0.256 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.538 ^1.011 ^0.176 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.598 ^0.969 ^0.109 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.63 ^0.94 ^0.071 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.622 ^0.946 ^0.079 ~ ~