#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.196 ^-0.406 ^0.471 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.205 ^-0.392 ^0.465 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.217 ^-0.382 ^0.457 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.231 ^-0.376 ^0.448 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.239 ^-0.375 ^0.443 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.245 ^-0.375 ^0.44 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.252 ^-0.375 ^0.436 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.259 ^-0.376 ^0.432 ~ ~