#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.437 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.445 ^-0.38 ^0.238 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.455 ^-0.387 ^0.222 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.467 ^-0.395 ^0.202 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.478 ^-0.404 ^0.178 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.489 ^-0.414 ^0.151 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.499 ^-0.424 ^0.123 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.506 ^-0.434 ^0.094 ~ ~