#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-4.8169f,-30f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-4.7354f,-29.3466f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-4.453f,-27.5464f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-4.0124f,-24.8394f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-3.4564f,-21.4656f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-2.8278f,-17.6652f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-2.1693f,-13.678f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-1.5236f,-9.7442f,0f]