#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.413 ^1.005 ^0.488 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.427 ^1.001 ^0.461 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.444 ^0.993 ^0.435 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.455 ^0.985 ^0.42 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.449 ^0.981 ^0.424 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.418 ^0.987 ^0.453 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.362 ^1 ^0.495 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.298 ^1.01 ^0.539 ~ ~