#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [16.6337f,28.2174f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [16.4179f,27.0775f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [16.1898f,25.8677f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [15.9496f,24.595f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [15.6972f,23.2663f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [15.4326f,21.8883f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [15.1558f,20.4681f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [14.8668f,19.0125f,0f]