#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.811 ^0.313 ^-0.073 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.808 ^0.314 ^-0.087 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.806 ^0.314 ^-0.103 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.804 ^0.314 ^-0.121 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.802 ^0.312 ^-0.14 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.801 ^0.309 ^-0.162 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.8 ^0.306 ^-0.185 ~ ~