#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.205 ^1.011 ^-0.478 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.283 ^1.055 ^-0.368 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.372 ^1.075 ^-0.244 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.446 ^1.073 ^-0.128 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.478 ^1.068 ^-0.058 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.5 ^1.062 ^0.009 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.516 ^1.054 ^0.078 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.524 ^1.046 ^0.148 ~ ~