#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [19.1542f,79.0349f,25.1455f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0.0042f,78.7013f,13.3639f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-15.0321f,76.5715f,4.2412f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-22.0761f,73.2525f,0.2728f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-21.3617f,69.9587f,-0.1578f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-16.8055f,65.4997f,-0.1471f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-10.5316f,60.2603f,-0.0364f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-4.3708f,54.9302f,0.0912f]