#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.512 ^-0.442 ^0.066 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.515 ^-0.449 ^0.04 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.517 ^-0.454 ^0.018 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.517 ^-0.456 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.517 ^-0.454 ^-0.016 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.515 ^-0.446 ^-0.029 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.513 ^-0.434 ^-0.039 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.511 ^-0.42 ^-0.046 ~ ~