#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.245 ^-0.421 ^0.451 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.25 ^-0.418 ^0.447 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.265 ^-0.414 ^0.438 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.286 ^-0.409 ^0.424 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.311 ^-0.404 ^0.404 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.338 ^-0.399 ^0.381 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.364 ^-0.393 ^0.354 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.388 ^-0.388 ^0.326 ~ ~