#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.689 ^0.312 ^-0.435 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.699 ^0.313 ^-0.417 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.71 ^0.313 ^-0.398 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.721 ^0.313 ^-0.376 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.733 ^0.314 ^-0.353 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.744 ^0.314 ^-0.329 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.754 ^0.314 ^-0.303 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.764 ^0.314 ^-0.276 ~ ~