#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [4.3395f,-12.4074f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [2.693f,-15.7154f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [1.0713f,-18.9062f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-0.4669f,-21.8801f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-1.8626f,-24.537f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-3.0574f,-26.7773f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-3.9924f,-28.5012f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-4.609f,-29.6087f,0f]