#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.502 ^0.004 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.523 ^0.044 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.548 ^0.095 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.563 ^0.124 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-0.549 ^0.097 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-0.516 ^0.031 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-0.5 ^0 ~ ~