#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.312 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.251 ^-0.293 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.252 ^-0.046 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.17 ^0.284 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^0.05 ^0.486 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^0.059 ^0.441 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^0.234 ^0.165 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.312 ^0 ~ ~