#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.5 ^1.001 ^-0.293 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.5 ^1.002 ^-0.022 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.5 ^0.919 ^0.327 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.5 ^0.8 ^0.487 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.5 ^0.795 ^0.298 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.5 ^0.977 ^0.064 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.5 ^1.062 ^0 ~ ~