#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [32.6323f,1.3765f,1.8444f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [42.8095f,1.0257f,1.3743f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [50f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [53.9275f,-2.7316f,-4.7633f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [54.792f,-6.6529f,-11.9332f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [54.3351f,-10.5696f,-17.819f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [54.2979f,-13.2876f,-18.73f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [54.9322f,-14.0392f,-14.2321f]