#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.147 ^-0.443 ^0.063 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.097 ^-0.436 ^-0.065 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.055 ^-0.44 ^-0.159 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.024 ^-0.445 ^-0.212 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.003 ^-0.445 ^-0.216 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.021 ^-0.436 ^-0.095 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.041 ^-0.467 ^0.194 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.048 ^-0.62 ^0.57 ~ ~