#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [67.9358f,-14.2063f,-6.0557f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [67.8141f,-13.978f,4.3783f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [67.7109f,-13.4347f,15.4324f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [67.9071f,-12.6569f,25.4693f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [68.6835f,-11.7252f,32.8516f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [70.3941f,-10.6889f,35.9795f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [74.3365f,-9.2252f,34.2837f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [80.0526f,-7.4125f,28.8224f]