#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.147 ^-1.347 ^1.237 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.078 ^-1.368 ^1.26 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.026 ^-1.378 ^1.273 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.013 ^-1.36 ^1.278 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.059 ^-1.32 ^1.275 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.117 ^-1.268 ^1.262 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.185 ^-1.209 ^1.236 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.255 ^-1.141 ^1.192 ~ ~