#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.114 ^-1.066 ^1.066 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.197 ^-1.108 ^1.075 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.272 ^-1.166 ^1.086 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.326 ^-1.23 ^1.1 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.351 ^-1.282 ^1.116 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.345 ^-1.307 ^1.135 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.299 ^-1.32 ^1.167 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.227 ^-1.33 ^1.204 ~ ~