#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.317 ^-1.057 ^1.127 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.349 ^-0.974 ^1.055 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.361 ^-0.888 ^0.97 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.36 ^-0.786 ^0.855 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.343 ^-0.683 ^0.713 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.309 ^-0.59 ^0.553 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.26 ^-0.516 ^0.383 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.204 ^-0.467 ^0.216 ~ ~