#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.001 ^-2.514 ^0.776 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.003 ^-2.496 ^0.791 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.01 ^-2.47 ^0.817 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.013 ^-2.441 ^0.848 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.01 ^-2.415 ^0.878 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.003 ^-2.397 ^0.903 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.004 ^-2.388 ^0.924 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.007 ^-2.392 ^0.941 ~ ~