#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [116.8243f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [116.8302f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [116.8272f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [116.8146f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [116.792f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [116.7589f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [116.7147f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [116.659f,0f,0f]