#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.438 ^-3.24 ^0.356 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.438 ^-3.24 ^0.356 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.438 ^-3.24 ^0.356 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.438 ^-3.24 ^0.356 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.438 ^-3.24 ^0.356 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.438 ^-3.24 ^0.356 ~ ~