#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.437 ^-0.443 ^0.277 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.437 ^-0.533 ^0.314 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.437 ^-0.645 ^0.36 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.436 ^-0.774 ^0.412 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.435 ^-0.919 ^0.471 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.434 ^-1.081 ^0.534 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.432 ^-1.253 ^0.593 ~ ~