#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [55.4621f,-0.8812f,3.2653f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [80.1386f,-0.6453f,2.5861f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [100.6897f,-0.3137f,1.3764f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [116.1828f,0.2213f,-1.059f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [122.3299f,2.8823f,-13.7806f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [116.4533f,5.1151f,-24.4772f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [116.8737f,3.8839f,-18.6695f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [117.9894f,0.2109f,-1.2383f]