#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-15.629f,-4.2597f,39.0387f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-14.1344f,-3.9419f,30.6527f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-15.0263f,-3.1962f,22.7909f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-16.8991f,-1.623f,16.654f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-16.659f,1.1309f,10.158f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-11.6053f,4.9487f,2.9352f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [9.8116f,10.0886f,-5.2676f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [46.123f,15.7196f,-14.0941f]