#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [115.5515f,0f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [115.3516f,0f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [115.1345f,0f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [113.8141f,0f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [107.302f,0f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [98.7331f,0f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [91.2865f,0f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [88.1412f,0f,0f]