#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-35.1285f,-0.8657f,2.4376f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-22.5302f,-1.2446f,1.4444f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-13.8994f,-1.9391f,0.9484f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-9.5807f,-4.3034f,-0.5698f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-8.6944f,-7.6795f,-2.7402f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-10.5232f,-10.4898f,-3.446f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-13.4213f,-11.8732f,-0.6326f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-17.2248f,-11.4019f,5.0789f]