#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-22.9592f,-10.0692f,12.8445f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-28.9191f,-8.3762f,22.1741f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-33.3472f,-6.7452f,32.3166f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-34.6214f,-5.6315f,42.2129f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-33.7578f,-4.9352f,49.6851f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-31.2987f,-4.5863f,53.0303f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-26.5474f,-4.4968f,51.7054f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-20.5778f,-4.4604f,46.5777f]