#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.145 ^-0.546 ^1.116 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.12 ^-0.472 ^0.997 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.13 ^-0.408 ^0.874 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.165 ^-0.345 ^0.72 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.225 ^-0.294 ^0.543 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.303 ^-0.267 ^0.352 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.392 ^-0.267 ^0.157 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.481 ^-0.297 ^-0.028 ~ ~