#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~