#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.496 ^-1.625 ^0.549 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.472 ^-1.725 ^0.556 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.428 ^-1.823 ^0.566 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.373 ^-1.901 ^0.577 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.322 ^-1.949 ^0.586 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.293 ^-1.962 ^0.593 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.291 ^-1.954 ^0.597 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.313 ^-1.926 ^0.601 ~ ~