#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.369 ^-1.898 ^0.143 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.369 ^-1.899 ^0.143 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.369 ^-1.901 ^0.142 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.369 ^-1.903 ^0.142 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.369 ^-1.905 ^0.142 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.369 ^-1.906 ^0.141 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.369 ^-1.908 ^0.141 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.369 ^-1.909 ^0.141 ~ ~