#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.373 ^-2.16 ^0.201 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.319 ^-2.209 ^0.186 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.349 ^-2.186 ^0.187 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.419 ^-2.11 ^0.201 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.441 ^-2.079 ^0.206 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.442 ^-2.075 ^0.203 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.439 ^-2.074 ^0.198 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.436 ^-2.072 ^0.194 ~ ~