#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.369 ^-1.743 ^0.125 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.369 ^-1.82 ^0.137 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.369 ^-1.876 ^0.147 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.369 ^-1.937 ^0.157 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.369 ^-1.933 ^0.156 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.369 ^-1.901 ^0.151 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.369 ^-1.877 ^0.147 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.369 ^-1.876 ^0.147 ~ ~