#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-66.108f,-4.5737f,5.2172f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-24.9844f,-4.4199f,2.9668f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [8.3595f,-3.6367f,0.658f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [29.2077f,-2.5703f,-2.4618f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [35.6211f,0.2997f,-15.4446f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [29.8797f,2.4271f,-25.843f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [30.3533f,1.2632f,-20.0247f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [31.4329f,-2.3212f,-2.6122f]