#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.736 ^-0.716 ^1.618 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.869 ^-0.875 ^1.629 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.972 ^-1.064 ^1.645 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^1.025 ^-1.251 ^1.668 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^1.03 ^-1.395 ^1.699 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.996 ^-1.469 ^1.737 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.917 ^-1.495 ^1.799 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.807 ^-1.501 ^1.872 ~ ~