#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.433 ^-1.539 ^0.48 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.429 ^-1.682 ^0.48 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.431 ^-1.771 ^0.454 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.443 ^-1.82 ^0.423 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.492 ^-1.821 ^0.396 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.512 ^-1.818 ^0.387 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.503 ^-1.899 ^0.366 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.443 ^-2.054 ^0.331 ~ ~