#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [109.5224f,0f,0f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [92.7503f,0f,0f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [92.8079f,0f,0f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [117.8366f,0f,0f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [154.7308f,0f,0f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [-173.2896f,0f,0f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [-162.9165f,0f,0f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [179.9827f,0f,0f]