#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.789 ^-3.215 ^1.272 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.806 ^-3.393 ^1.229 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0.813 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0.813 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0.813 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0.813 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0.813 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0.813 ^-3.518 ^1.2 ~ ~