#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.369 ^-1.3 ^0.253 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.369 ^-1.286 ^0.258 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.369 ^-1.302 ^0.258 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.369 ^-1.341 ^0.255 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.369 ^-1.396 ^0.252 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.369 ^-1.461 ^0.249 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.369 ^-1.544 ^0.245 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.369 ^-1.645 ^0.239 ~ ~