#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [132.0627f,-5.8696f,7.0223f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [132.0586f,-8.286f,9.6262f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [132.0643f,-5.3128f,6.422f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [132.2778f,0.1964f,0.4756f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [132.9576f,5.7387f,-5.5274f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [134.3622f,8.8111f,-8.9017f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [136.5065f,8.5707f,-8.7395f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [139.4678f,6.7344f,-6.8944f]