#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [44.544f,-0.9921f,-0.7868f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [41.7867f,0.0183f,-1.6105f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [37.9317f,2.2097f,-3.7304f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [33.482f,4.8919f,-6.3522f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [29.0217f,7.2388f,-8.608f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [25.1282f,8.4199f,-9.6279f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [21.9949f,6.8418f,-7.7046f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [19.7685f,0.5258f,-0.7175f]