#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.369 ^-1.889 ^0.145 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.369 ^-1.884 ^0.145 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.369 ^-1.88 ^0.146 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.369 ^-1.853 ^0.151 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.369 ^-1.748 ^0.17 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.369 ^-1.611 ^0.194 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.369 ^-1.471 ^0.219 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.369 ^-1.358 ^0.241 ~ ~