#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [97.503f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [107.6213f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [114.98f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [122.95f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [122.4407f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [118.223f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [115.0676f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [114.9831f,0f,0f]