#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.369 ^-1.911 ^0.141 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.369 ^-1.912 ^0.14 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.369 ^-1.913 ^0.14 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.369 ^-1.914 ^0.14 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.369 ^-1.915 ^0.14 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.369 ^-1.916 ^0.14 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.369 ^-1.917 ^0.139 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.369 ^-1.917 ^0.139 ~ ~