#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [86.5951f,-5.3881f,21.0444f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [93.2349f,-3.2892f,12.3988f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [99.1912f,-1.2533f,4.3343f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [103.214f,0.6277f,-1.9482f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [105.6603f,2.7598f,-8.4095f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [106.6981f,5.0449f,-15.1852f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [106.1653f,7.192f,-21.4685f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [103.8999f,8.9102f,-26.4529f]