#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-142.709f,-2.4693f,11.4791f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-141.8907f,-4.1725f,19.5774f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-140.4314f,-3.2724f,15.3899f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-139.417f,-0.7828f,3.681f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-139.07f,0.1293f,-0.7528f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-138.8979f,0.0291f,-1.1585f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-138.8503f,-0.2899f,-0.6672f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [-139.1543f,-0.5162f,0.0376f]