#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.369 ^-1.902 ^0.146 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.369 ^-1.901 ^0.146 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.369 ^-1.899 ^0.146 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.369 ^-1.897 ^0.146 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.369 ^-1.895 ^0.146 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.369 ^-1.893 ^0.146 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.369 ^-1.89 ^0.147 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.369 ^-1.887 ^0.147 ~ ~