#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [31.2737f,-0.0356f,12.3238f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [33.8477f,-0.6775f,15.977f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [37.2834f,1.5109f,6.3942f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [41.2971f,4.85f,-8.618f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [45.0148f,7.7578f,-21.8126f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [47.5308f,8.6782f,-25.9695f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [48.7423f,7.0219f,-18.2461f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [49.1421f,3.9662f,-4.0872f]