#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.228 ^-0.819 ^1.863 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.098 ^-0.801 ^1.87 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.034 ^-0.806 ^1.878 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.144 ^-0.831 ^1.888 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.207 ^-0.864 ^1.902 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.201 ^-0.891 ^1.922 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.101 ^-0.939 ^1.96 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.062 ^-1.023 ^2.001 ~ ~