#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.342 ^-1.737 ^0.614 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.356 ^-1.7 ^0.609 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.376 ^-1.653 ^0.595 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.401 ^-1.59 ^0.572 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.427 ^-1.514 ^0.541 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.449 ^-1.429 ^0.502 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.464 ^-1.341 ^0.454 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.472 ^-1.255 ^0.402 ~ ~