#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-178.1037f,0f,0f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [172.0099f,0f,0f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [154.8045f,0f,0f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [136.4417f,0f,0f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [123.083f,0f,0f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [120.7994f,0f,0f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [130.9727f,0f,0f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [148.1421f,0f,0f]