#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.369 ^-1.88 ^0.148 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.369 ^-1.882 ^0.147 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.369 ^-1.883 ^0.147 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.369 ^-1.884 ^0.147 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.369 ^-1.885 ^0.147 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.369 ^-1.887 ^0.147 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.369 ^-1.888 ^0.147 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.369 ^-1.889 ^0.147 ~ ~