#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.751 ^-2.764 ^0.915 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.814 ^-2.748 ^0.856 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.665 ^-2.905 ^0.752 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.368 ^-3.075 ^0.622 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.062 ^-3.15 ^0.499 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.048 ^-3.16 ^0.42 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.123 ^-3.159 ^0.391 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.44 ^-3.094 ^0.391 ~ ~