#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [100.5085f,0f,0f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [94.4101f,0f,0f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [90f,0f,0f]