#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.796 ^-2.344 ^1.045 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.801 ^-2.333 ^1.042 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.81 ^-2.327 ^1.03 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.823 ^-2.325 ^1.013 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.837 ^-2.322 ^0.998 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.849 ^-2.311 ^0.997 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.851 ^-2.267 ^1.035 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.817 ^-2.166 ^1.138 ~ ~