#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.369 ^-1.884 ^0.147 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.369 ^-1.881 ^0.148 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.369 ^-1.877 ^0.148 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.369 ^-1.857 ^0.15 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.369 ^-1.774 ^0.157 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.369 ^-1.667 ^0.166 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.369 ^-1.558 ^0.176 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.369 ^-1.471 ^0.184 ~ ~