#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [18.0982f,-5.1701f,6.5898f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [17.0323f,-7.7088f,9.2699f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [16.0123f,-4.8504f,6.1406f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [15.2749f,0.553f,0.2635f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [15.1008f,5.9993f,-5.6771f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [15.7588f,8.9857f,-8.9953f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [17.2638f,8.6683f,-8.786f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [19.6923f,6.7644f,-6.9063f]