#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.483 ^-1.986 ^0.239 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.503 ^-1.917 ^0.25 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.493 ^-1.954 ^0.237 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.454 ^-2.053 ^0.213 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.434 ^-2.091 ^0.204 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.433 ^-2.093 ^0.203 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.435 ^-2.084 ^0.202 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.439 ^-2.072 ^0.202 ~ ~