#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.612 ^-3.052 ^0.728 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.648 ^-3.07 ^0.757 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.603 ^-3.19 ^0.748 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.512 ^-3.362 ^0.716 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.407 ^-3.55 ^0.672 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.338 ^-3.727 ^0.635 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.332 ^-3.883 ^0.612 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.36 ^-4.025 ^0.584 ~ ~