#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [113.2292f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [113.1746f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [113.0989f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [113.0036f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [112.8901f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [112.7598f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [112.6143f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [112.4548f,0f,0f]