#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.828 ^-3.335 ^1.155 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.818 ^-3.44 ^1.183 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.812 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.812 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.812 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.812 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.812 ^-3.518 ^1.2 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.812 ^-3.518 ^1.2 ~ ~