#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.721 ^-0.624 ^0.703 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.717 ^-0.795 ^0.863 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.713 ^-0.942 ^0.978 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.716 ^-1.106 ^1.074 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.717 ^-1.186 ^1.119 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.706 ^-1.196 ^1.134 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.675 ^-1.161 ^1.143 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.626 ^-1.093 ^1.141 ~ ~