#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.795 ^-1.471 ^1.769 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.854 ^-1.344 ^1.703 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.901 ^-1.188 ^1.625 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.951 ^-0.97 ^1.51 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.986 ^-0.708 ^1.345 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.99 ^-0.426 ^1.121 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.953 ^-0.163 ^0.84 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.88 ^0.046 ^0.519 ~ ~