#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-137.2817f,5.0455f,-14.3351f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-153.3822f,4.431f,-10.7512f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-166.1462f,3.9136f,-7.5224f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-174.2494f,3.4861f,-4.8223f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-176.3653f,3.1287f,-2.8299f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-165.7962f,2.5591f,-0.5192f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-139.5234f,1.6562f,1.5614f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-103.4136f,0.5442f,2.4055f]