#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.836 ^-0.606 ^-0.299 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.802 ^-0.595 ^-0.406 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.778 ^-0.586 ^-0.48 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.762 ^-0.571 ^-0.518 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.751 ^-0.545 ^-0.514 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.735 ^-0.471 ^-0.396 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.715 ^-0.392 ^-0.105 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.702 ^-0.42 ^0.312 ~ ~