#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-0.489 ^-0.003 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-0.492 ^-0.002 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-0.494 ^-0.002 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^-0.496 ^-0.001 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^-0.498 ^0 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^-0.5 ^0 ~ ~