#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [1.8094f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [0.3107f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0f,0f,0f]