#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-0.561 ^-0.003 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-0.571 ^-0.003 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-0.582 ^-0.004 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-0.592 ^-0.004 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-0.603 ^-0.004 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-0.613 ^-0.004 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-0.623 ^-0.005 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-0.633 ^-0.005 ~ ~