#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-0.715 ^0.012 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^-0.727 ^0.019 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^-0.737 ^0.027 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^-0.746 ^0.035 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.753 ^0.042 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-0.758 ^0.049 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-0.76 ^0.055 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-0.759 ^0.06 ~ ~