#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [1.2357f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [2.7331f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [4.4666f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [6.4102f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [8.5381f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [10.8246f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [13.2438f,0f,0f]