#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^0.289 ^-0.304 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^0.293 ^-0.284 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^0.309 ^-0.226 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^0.33 ^-0.122 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^0.338 ^0.002 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^0.329 ^0.115 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^0.314 ^0.183 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^0.305 ^0.182 ~ ~