#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-0.437 ^0.828 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-0.379 ^0.809 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-0.247 ^0.749 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-0.084 ^0.649 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^0.076 ^0.515 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^0.208 ^0.365 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^0.294 ^0.227 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^0.338 ^-0.043 ~ ~