#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-84.0583f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-87.5802f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-89.5081f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-90.0781f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-89.5263f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-88.0891f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-86.0025f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-83.5028f,0f,0f]