#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [40.55f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [47.2208f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [54.0085f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [60.8413f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [67.6475f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [74.3553f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [80.8929f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [87.1887f,0f,0f]