#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.5 ^1.023 ^-0.123 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.5 ^1.06 ^-0.034 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.5 ^1.062 ^0 ~ ~