#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.438 ^-0.692 ^0.271 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.438 ^-0.713 ^0.269 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.438 ^-0.732 ^0.267 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.438 ^-0.75 ^0.265 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.438 ^-0.766 ^0.263 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.438 ^-0.78 ^0.262 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.438 ^-0.796 ^0.261 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.438 ^-0.818 ^0.261 ~ ~