#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.438 ^-0.892 ^0.306 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.438 ^-0.861 ^0.313 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.438 ^-0.789 ^0.319 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.438 ^-0.691 ^0.318 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.438 ^-0.582 ^0.306 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.438 ^-0.478 ^0.283 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.438 ^-0.396 ^0.258 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.438 ^-0.306 ^0.204 ~ ~