#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [42.8201f,0.1959f,-22.1158f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [43.5985f,0.8718f,-22.5775f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [46.8641f,2.6152f,-22.9632f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [52.1313f,6.1403f,-24.8021f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [58.1192f,11.2179f,-27.2598f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [62.6461f,16.7722f,-28.964f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [63.7418f,20.9502f,-29.3167f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [60.3717f,22.1911f,-27.9274f]