#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.603 ^0.147 ^-0.512 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.604 ^0.158 ^-0.495 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.606 ^0.189 ^-0.445 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.609 ^0.236 ^-0.358 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.612 ^0.277 ^-0.252 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.616 ^0.302 ^-0.148 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.62 ^0.311 ^-0.071 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.625 ^0.314 ^-0.03 ~ ~