#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [13.301f,-10.0553f,59.4118f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [14.4362f,-12.3764f,60.6587f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [15.9552f,-13.0411f,59.0484f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [16.4662f,-12.2029f,55.5789f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [14.7462f,-10.7348f,52.2682f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [11.3436f,-7.9761f,48.2973f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [7.2779f,-4.0341f,44.0504f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [3.6278f,0.8616f,39.7848f]