#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.438 ^-0.25 ^0.141 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.438 ^-0.242 ^0.133 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.438 ^-0.237 ^0.128 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.438 ^-0.234 ^0.124 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.438 ^-0.233 ^0.122 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.438 ^-0.234 ^0.122 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.438 ^-0.236 ^0.124 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.438 ^-0.24 ^0.128 ~ ~