#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [131.268f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [135.6396f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [139.4406f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [142.5446f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [144.8254f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [146.1564f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [146.4112f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [145.4634f,0f,0f]