#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.438 ^-0.509 ^0.272 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.438 ^-0.532 ^0.274 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.438 ^-0.555 ^0.275 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.438 ^-0.578 ^0.275 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.438 ^-0.602 ^0.275 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.438 ^-0.625 ^0.275 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.438 ^-0.648 ^0.274 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.438 ^-0.671 ^0.272 ~ ~