#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.781 ^0.238 ^0.158 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.775 ^0.219 ^0.194 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.77 ^0.199 ^0.23 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.764 ^0.177 ^0.266 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.758 ^0.153 ^0.301 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.752 ^0.127 ^0.336 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.746 ^0.101 ^0.369 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.74 ^0.073 ^0.401 ~ ~