#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.438 ^-0.383 ^0.254 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.438 ^-0.377 ^0.251 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~