#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [7.1475f,21.2178f,22.9724f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [8.491f,20.5514f,25.5054f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [9.3089f,19.067f,29.5876f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [10.1044f,15.1893f,35.511f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [11.0919f,9.7978f,41.3681f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [11.9016f,4.003f,46.9871f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [12.5719f,-1.5293f,52.0915f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [13.2082f,-6.4013f,56.065f]