#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.437 ^-0.245 ^0.133 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.437 ^-0.251 ^0.14 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.437 ^-0.265 ^0.158 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.437 ^-0.288 ^0.185 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.437 ^-0.318 ^0.213 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.437 ^-0.349 ^0.235 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.437 ^-0.373 ^0.249 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.437 ^-0.386 ^0.255 ~ ~