#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.641 ^-0.248 ^0.701 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.637 ^-0.195 ^0.667 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.633 ^-0.081 ^0.581 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.63 ^0.052 ^0.451 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.627 ^0.173 ^0.292 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.623 ^0.26 ^0.125 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.619 ^0.306 ^-0.022 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.615 ^0.267 ^-0.288 ~ ~