#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-135.202f,36.8837f,-149.2061f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-134.6978f,40.372f,-146.7906f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-136.471f,45.9976f,-145.6555f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-96.9359f,68.2484f,-97.4618f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-19.4628f,45.3343f,-14.1083f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-6.0875f,7.9727f,-0.8475f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-0.592f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [2.2856f,0f,0f]