#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.437 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.437 ^-0.386 ^0.253 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.437 ^-0.398 ^0.255 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.437 ^-0.413 ^0.258 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.437 ^-0.429 ^0.262 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.437 ^-0.447 ^0.265 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.437 ^-0.466 ^0.267 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.437 ^-0.487 ^0.27 ~ ~