#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [3.8707f,7.7289f,-57.0695f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [5.5934f,10.015f,-58.2393f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [7.2318f,10.6406f,-56.7627f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [6.7213f,9.7829f,-53.5705f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [3.3539f,8.3301f,-50.52f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-2.3088f,5.6386f,-46.8433f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-8.811f,1.8227f,-42.8798f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-14.6486f,-2.8945f,-38.8543f]