#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.437 ^-0.839 ^0.262 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.437 ^-0.859 ^0.265 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.437 ^-0.876 ^0.269 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.437 ^-0.89 ^0.274 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.437 ^-0.9 ^0.28 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.437 ^-0.906 ^0.286 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.437 ^-0.907 ^0.293 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.437 ^-0.903 ^0.299 ~ ~