#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-0.245f,-22.4305f,-22.0064f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0.8075f,-21.8674f,-24.5538f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [1.14f,-20.5453f,-28.6008f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [1.3676f,-16.8965f,-34.3895f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [1.9625f,-11.715f,-40.0382f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [2.526f,-6.0861f,-45.384f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [3.0705f,-0.6683f,-50.1967f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [3.6597f,4.1241f,-53.9329f]