#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
execute store result score @s aj.id run scoreboard players add .aj.last_id aj.i 1
execute at @s run function warden:summon/zzz/execute/3
tag @s remove new
scoreboard players set @s aj.warden.animation.warden.emerge.loopMode 0
scoreboard players set @s aj.warden.animation.warden.dig.loopMode 1
scoreboard players set @s aj.warden.animation.warden.roar.loopMode 0
scoreboard players set @s aj.warden.animation.warden.sniff.loopMode 0
scoreboard players set @s aj.warden.animation.warden.attack.loopMode 0
scoreboard players set @s aj.warden.animation.warden.hurt.loopMode 0
scoreboard players set @s aj.warden.animation.warden.sonic_boom.loopMode 0
scoreboard players set @s aj.frame 0
scoreboard players set @s aj.warden.animating 0