#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^-0.703 ^0.427 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0 ^-0.704 ^0.43 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^-0.705 ^0.432 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0 ^-0.706 ^0.433 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^-0.707 ^0.434 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0 ^-0.707 ^0.434 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^-0.708 ^0.434 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0 ^-0.708 ^0.432 ~ ~