#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.502 ^-0.005 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.503 ^-0.011 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.505 ^-0.019 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.506 ^-0.028 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-0.508 ^-0.038 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-0.51 ^-0.049 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-0.512 ^-0.061 ~ ~