#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.warden.bone.body] run function warden:animations/animation.warden.roar/tree/body_display_top
execute if entity @s[tag=aj.warden.bone.right_ribcage] run function warden:animations/animation.warden.roar/tree/right_ribcage_display_top
execute if entity @s[tag=aj.warden.bone.left_ribcage] run function warden:animations/animation.warden.roar/tree/left_ribcage_display_top
execute if entity @s[tag=aj.warden.bone.head] run function warden:animations/animation.warden.roar/tree/head_display_top
execute if entity @s[tag=aj.warden.bone.right_tendril] run function warden:animations/animation.warden.roar/tree/right_tendril_display_top
execute if entity @s[tag=aj.warden.bone.left_tendril] run function warden:animations/animation.warden.roar/tree/left_tendril_display_top
execute if entity @s[tag=aj.warden.bone.right_arm] run function warden:animations/animation.warden.roar/tree/right_arm_display_top
execute if entity @s[tag=aj.warden.bone.left_arm] run function warden:animations/animation.warden.roar/tree/left_arm_display_top
execute if entity @s[tag=aj.warden.bone.right_leg] run function warden:animations/animation.warden.roar/tree/right_leg_display_top
execute if entity @s[tag=aj.warden.bone.left_leg] run function warden:animations/animation.warden.roar/tree/left_leg_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~