#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [42.8615f,7.9064f,-4.5571f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [44.6895f,9.6506f,-6.7308f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [44.7825f,9.872f,-7.6394f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [44.3667f,9.9099f,-8.4241f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [43.3738f,9.757f,-9.0658f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [42.7403f,9.5687f,-9.3421f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [41.8414f,9.2589f,-9.5492f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [40.7002f,8.8419f,-9.683f]