#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-57.3527f,0.1784f,0.4884f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-57.3925f,-0.1794f,-0.511f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-53.9312f,-1.3167f,-4.7267f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-46.5867f,-1.8389f,-11.1365f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-36.9219f,-0.5784f,-18.5755f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-26.6157f,2.7888f,-25.4783f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-17.0179f,7.4823f,-30.395f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-8.9462f,11.9352f,-32.4191f]