#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.049 ^-0.313 ^1.061 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.033 ^-0.382 ^1.106 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.017 ^-0.411 ^1.128 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.002 ^-0.415 ^1.138 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.01 ^-0.412 ^1.143 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.015 ^-0.417 ^1.151 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.01 ^-0.425 ^1.157 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.001 ^-0.429 ^1.162 ~ ~