#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-43.2417f,0.7345f,2.4473f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-45.9509f,0.7738f,2.4333f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-48.458f,0.7893f,2.3642f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-50.7291f,0.7764f,2.2352f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-52.7303f,0.7307f,2.0411f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-54.4276f,0.6492f,1.7761f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-55.7866f,0.5298f,1.434f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-56.7732f,0.3722f,1.0076f]