#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-1.3406f,0.0002f,0.0273f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-3.0212f,0.002f,0.1046f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-5.008f,0.0074f,0.2249f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-7.2668f,0.0184f,0.3813f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-9.7639f,0.0371f,0.5664f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-12.4652f,0.0653f,0.773f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-15.3367f,0.104f,0.9938f]