#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-3.0297f,14.365f,-31.2035f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [3.3725f,10.3512f,-20.1373f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [6.2504f,-0.5477f,-2.8218f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [4.7145f,-11.2787f,14.0097f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [2.7138f,-15.7081f,23.0491f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [4.277f,-12.294f,18.912f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [6.5478f,-3.7093f,6.5585f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [6.7276f,6.7317f,-8.344f]