#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-18.3444f,0.1537f,1.2213f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-21.4545f,0.214f,1.4483f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-24.6329f,0.2839f,1.6675f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-27.8456f,0.3613f,1.8718f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-31.059f,0.4431f,2.0546f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-34.239f,0.526f,2.2093f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-37.352f,0.6054f,2.3301f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-40.3641f,0.6766f,2.4112f]