#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [5.4907f,0.1644f,-1.7045f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [3.7982f,0.0776f,-1.1493f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [2.3026f,0.028f,-0.6718f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [1.0285f,0.0054f,-0.2847f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,0f]