#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.007 ^0.222 ^-0.492 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.007 ^0.213 ^-0.516 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.007 ^0.203 ^-0.537 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.007 ^0.195 ^-0.552 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.006 ^0.188 ^-0.563 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.005 ^0.182 ^-0.569 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.004 ^0.177 ^-0.568 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.003 ^0.174 ^-0.561 ~ ~