#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.roar/tree/head_root_0-63
execute if score .this aj.frame matches 64..85 run function warden:animations/animation.warden.roar/tree/head_root_64-85