#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [23.1268f,3.0071f,-7.1875f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [20.7566f,2.4249f,-6.5437f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [18.3848f,1.9023f,-5.8582f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [16.0353f,1.4454f,-5.1451f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [13.7326f,1.0574f,-4.4194f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [11.5016f,0.7388f,-3.6967f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [9.3675f,0.4873f,-2.993f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [7.3555f,0.2981f,-2.3239f]