#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.001 ^0.273 ^0.154 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.001 ^0.286 ^0.108 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0 ^0.297 ^0.067 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0 ^0.305 ^0.03 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0 ^0.312 ^0 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0 ^0.312 ^0 ~ ~