#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-83.3936f,3.2716f,13.1883f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-95.7026f,4.0313f,14.9338f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-107.356f,4.7767f,16.4772f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-118.0409f,5.4555f,17.7611f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-127.4488f,6.0083f,18.7329f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-135.2749f,6.3691f,19.3444f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-141.2166f,6.4674f,19.552f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-145.5893f,5.9094f,19.2701f]