#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.438 ^-0.737 ^0.599 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.438 ^-0.72 ^0.587 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.438 ^-0.702 ^0.573 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.438 ^-0.683 ^0.558 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.438 ^-0.663 ^0.541 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.438 ^-0.643 ^0.524 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.438 ^-0.622 ^0.506 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.437 ^-0.6 ^0.487 ~ ~