#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.609 ^-0.243 ^0.867 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.613 ^-0.244 ^0.872 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.615 ^-0.245 ^0.878 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.615 ^-0.246 ^0.884 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.614 ^-0.245 ^0.89 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.614 ^-0.242 ^0.895 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.614 ^-0.238 ^0.9 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.614 ^-0.231 ^0.902 ~ ~