#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-1.3406f,0.0005f,0.0397f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-3.0212f,0.0045f,0.1519f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-5.0079f,0.0163f,0.3265f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-7.2667f,0.0403f,0.5528f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-9.7636f,0.0807f,0.8198f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-12.4646f,0.1412f,1.1164f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-15.3354f,0.2238f,1.4308f]