#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [7.3647f,14.0028f,-12.3655f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [8.3405f,16.0795f,-13.3087f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [9.0418f,14.2037f,-10.3896f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [8.8859f,10.6234f,-7.0213f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [8.5729f,5.8006f,-3.5751f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [8.7437f,0.2704f,-0.2538f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [9.6937f,-5.2752f,2.742f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [11.2565f,-10.1058f,5.2777f]