#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.789 ^-0.038 ^1.158 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.804 ^-0.059 ^1.157 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.799 ^-0.044 ^1.198 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.774 ^-0.021 ^1.281 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.724 ^0.011 ^1.384 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.65 ^0.042 ^1.492 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.559 ^0.065 ^1.591 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.466 ^0.078 ^1.67 ~ ~