#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.792 ^0.283 ^0.063 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.798 ^0.292 ^0.026 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.804 ^0.3 ^-0.008 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.808 ^0.307 ^-0.038 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~