#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [8.2945f,2.1887f,-3.0946f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [5.8051f,1.4773f,-2.2009f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [3.574f,0.882f,-1.3717f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [1.6297f,0.393f,-0.6306f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,0f]