#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.577 ^0.028 ^-0.542 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.572 ^0.032 ^-0.521 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.559 ^0.053 ^-0.419 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.541 ^0.08 ^-0.254 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.519 ^0.099 ^-0.048 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.498 ^0.097 ^0.177 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.482 ^0.072 ^0.391 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.474 ^0.033 ^0.57 ~ ~