#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-148.1278f,4.1226f,18.4258f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-148.6268f,1.388f,17.1706f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-147.2974f,-2.015f,15.6336f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-144.3379f,-5.7919f,13.9062f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-139.9256f,-9.6369f,12.04f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-134.2081f,-13.2361f,10.0462f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-127.303f,-16.2707f,7.9024f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-119.3085f,-18.4168f,5.5695f]