#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.713 ^0.205 ^-0.252 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.698 ^0.187 ^-0.283 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.684 ^0.168 ^-0.313 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.669 ^0.15 ^-0.343 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.656 ^0.132 ^-0.372 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.645 ^0.116 ^-0.399 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.634 ^0.1 ^-0.426 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.626 ^0.086 ^-0.451 ~ ~