#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.438 ^-0.353 ^0.154 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.438 ^-0.349 ^0.137 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.439 ^-0.346 ^0.119 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.439 ^-0.342 ^0.101 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.439 ^-0.339 ^0.084 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.439 ^-0.337 ^0.066 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.439 ^-0.334 ^0.05 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.439 ^-0.332 ^0.034 ~ ~