#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [22.3605f,6.7637f,-16.1614f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [20.1917f,5.478f,-14.7254f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [17.986f,4.3146f,-13.2017f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [15.7676f,3.2899f,-11.6182f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [13.5632f,2.4143f,-10.0058f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [11.4019f,1.6913f,-8.3971f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [9.3138f,1.1179f,-6.8258f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [7.3297f,0.685f,-5.3258f]