#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.519 ^0.992 ^-0.45 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.523 ^0.97 ^-0.525 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.526 ^0.945 ^-0.601 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.529 ^0.916 ^-0.675 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.532 ^0.885 ^-0.748 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.534 ^0.852 ^-0.817 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.536 ^0.818 ^-0.883 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.537 ^0.782 ^-0.944 ~ ~