#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [40.1489f,0f,-2.5359f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [40.6235f,0f,-4.1228f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [41.1919f,0f,-4.0542f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [41.782f,0f,-2.5141f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [42.4067f,0f,-0.1267f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [43.0464f,0f,2.5142f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [43.6816f,0f,4.8147f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [44.2925f,0f,6.1811f]