#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.439 ^-0.331 ^0.019 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.44 ^-0.33 ^0.006 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.44 ^-0.33 ^-0.005 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.439 ^-0.33 ^-0.015 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.439 ^-0.331 ^-0.022 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.439 ^-0.332 ^-0.026 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.439 ^-0.334 ^-0.028 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.438 ^-0.337 ^-0.026 ~ ~