#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.425 ^-0.843 ^0.696 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.425 ^-0.844 ^0.693 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.426 ^-0.845 ^0.689 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.426 ^-0.845 ^0.685 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.427 ^-0.844 ^0.679 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.429 ^-0.841 ^0.674 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.43 ^-0.838 ^0.668 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.432 ^-0.833 ^0.661 ~ ~