#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.473 ^-0.008 ^0.691 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.49 ^-0.049 ^0.749 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.518 ^-0.086 ^0.773 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.547 ^-0.117 ^0.779 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.57 ^-0.14 ^0.781 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.576 ^-0.155 ^0.79 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.565 ^-0.152 ^0.801 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.542 ^-0.136 ^0.81 ~ ~