#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [43.3648f,2.952f,0.7532f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [44.756f,9.2545f,-6.3254f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [43.75f,14.525f,-12.5192f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [42.0004f,18.6271f,-17.9766f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [40.1729f,20.3577f,-21.291f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [39.5168f,20.1505f,-21.812f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [38.6666f,19.6581f,-22.1646f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [37.6396f,18.9114f,-22.3461f]