#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.438 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.438 ^-0.374 ^0.244 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.438 ^-0.372 ^0.236 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.438 ^-0.37 ^0.226 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.438 ^-0.367 ^0.214 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.438 ^-0.364 ^0.201 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.438 ^-0.36 ^0.186 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.438 ^-0.356 ^0.171 ~ ~