#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.493 ^0.582 ^-1.181 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.507 ^0.574 ^-1.142 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.562 ^0.582 ^-0.95 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.639 ^0.588 ^-0.644 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.72 ^0.549 ^-0.272 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.789 ^0.451 ^0.11 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.833 ^0.311 ^0.451 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.85 ^0.17 ^0.718 ~ ~