#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.656 ^0.208 ^1.388 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.652 ^0.263 ^1.343 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.648 ^0.321 ^1.291 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.642 ^0.382 ^1.234 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.635 ^0.443 ^1.172 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.628 ^0.505 ^1.105 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.62 ^0.567 ^1.033 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.611 ^0.627 ^0.957 ~ ~