#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-18.3431f,0.274f,1.5843f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-21.4523f,0.3805f,1.872f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-24.6296f,0.5033f,2.146f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-27.8411f,0.6386f,2.397f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-31.053f,0.7813f,2.6162f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-34.2316f,0.925f,2.7958f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-37.3433f,1.0621f,2.9287f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-40.3544f,1.1844f,3.0089f]