#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.43 ^-0.774 ^0.653 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.429 ^-0.788 ^0.659 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.433 ^-0.778 ^0.666 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.437 ^-0.756 ^0.674 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.439 ^-0.737 ^0.682 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.44 ^-0.733 ^0.687 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.439 ^-0.745 ^0.692 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.437 ^-0.766 ^0.696 ~ ~