#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.607 ^0.086 ^-0.474 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.6 ^0.074 ^-0.494 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.595 ^0.064 ^-0.512 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.59 ^0.055 ^-0.527 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.585 ^0.047 ^-0.539 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.582 ^0.041 ^-0.546 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.579 ^0.036 ^-0.55 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.576 ^0.032 ^-0.548 ~ ~