#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.523 ^1.004 ^0.225 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.516 ^1.024 ^0.157 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.509 ^1.04 ^0.097 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.504 ^1.053 ^0.044 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.5 ^1.062 ^0 ~ ~