#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.574 ^0.03 ^-0.542 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.574 ^0.029 ^-0.521 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.581 ^0.032 ^-0.419 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.594 ^0.034 ^-0.254 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.61 ^0.024 ^-0.048 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.625 ^-0.007 ^0.177 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.635 ^-0.055 ^0.391 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.637 ^-0.11 ^0.57 ~ ~