#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.435 ^-0.322 ^0.019 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.435 ^-0.322 ^0.006 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.435 ^-0.321 ^-0.005 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.436 ^-0.322 ^-0.015 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.436 ^-0.324 ^-0.022 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.436 ^-0.326 ^-0.026 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.436 ^-0.329 ^-0.028 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.437 ^-0.334 ^-0.026 ~ ~