#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [43.3976f,2.2711f,1.4744f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [44.9916f,7.6792f,-4.7258f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [44.3517f,12.0617f,-9.9034f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [43.0378f,15.5317f,-14.4466f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [41.4563f,17.0882f,-17.2959f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [40.7942f,16.9384f,-17.7988f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [39.9114f,16.5428f,-18.1608f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [38.8281f,15.9276f,-18.379f]