#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-57.3523f,0.3164f,0.5769f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-57.3923f,-0.2759f,-0.5727f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-53.9143f,-2.0955f,-5.2943f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-46.5176f,-3.4254f,-12.6407f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-36.8362f,-2.7749f,-21.5036f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-26.7477f,0.423f,-30.1848f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-17.7618f,5.4225f,-37.0063f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-10.5907f,10.5082f,-40.8539f]