#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [85.3691f,-38.4576f,6.5084f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [82.4622f,-36.9455f,7.8867f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [79.6263f,-35.2935f,8.4321f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [77.488f,-34.3098f,8.7391f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [74.6758f,-33.1002f,9.4067f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [72.3107f,-31.8232f,9.8759f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [69.6654f,-30.3948f,10.358f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [66.7825f,-28.8299f,10.8192f]