#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-143.7327f,-5.4674f,-15.9487f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-144.9019f,-3.943f,-13.4125f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-144.3248f,-1.8818f,-10.381f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-142.0891f,0.5328f,-7.0303f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-138.2865f,3.0906f,-3.5056f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-133.0179f,5.5591f,0.0722f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-126.3992f,7.6903f,3.594f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-118.5675f,9.2285f,6.9457f]