#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [95.4914f,-39.2622f,-3.8788f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [94.4763f,-39.1462f,-3.8668f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [93.4677f,-39.044f,-3.7489f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [92.0686f,-39.1175f,-2.6773f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [91.0747f,-39.3119f,-1.1551f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [90.1677f,-39.5059f,0.6825f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [89.0624f,-39.5483f,2.69f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [87.5231f,-39.2625f,4.6988f]