#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [112.3301f,-39.1343f,-11.7611f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [119.0975f,-39.1411f,-14.4885f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [121.2539f,-39.3032f,-13.3343f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [120.561f,-39.6606f,-10.3114f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [118.7597f,-40.0183f,-7.4367f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [117.5578f,-40.1692f,-6.7321f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [116.353f,-40.2057f,-8.1882f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [114.5545f,-40.2242f,-10.5756f]