#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.579 ^-0.179 ^0.902 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.592 ^-0.181 ^0.899 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.605 ^-0.178 ^0.892 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.617 ^-0.17 ^0.88 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.628 ^-0.155 ^0.864 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.637 ^-0.141 ^0.848 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.647 ^-0.123 ^0.828 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.656 ^-0.102 ^0.804 ~ ~