#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.437 ^-0.375 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.437 ^-0.374 ^0.244 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.437 ^-0.372 ^0.236 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.437 ^-0.369 ^0.226 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.437 ^-0.366 ^0.214 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.437 ^-0.362 ^0.201 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.437 ^-0.358 ^0.186 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.437 ^-0.353 ^0.171 ~ ~