#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.739 ^0.133 ^0.444 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.747 ^0.157 ^0.394 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.755 ^0.18 ^0.344 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.762 ^0.202 ^0.294 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.769 ^0.221 ^0.244 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.776 ^0.239 ^0.196 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.783 ^0.255 ^0.149 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.789 ^0.269 ^0.105 ~ ~