#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [63.7007f,-27.1463f,11.2289f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [60.4546f,-25.3639f,11.561f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [57.0748f,-23.5048f,11.7939f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [53.5882f,-21.593f,11.9109f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [50.0188f,-19.6534f,11.9002f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [46.3884f,-17.7115f,11.7547f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [42.7175f,-15.7928f,11.4719f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [39.0258f,-13.9217f,11.0539f]