#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [5.7534f,0f,-0.0728f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [4.0104f,0f,-0.043f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [2.4563f,0f,-0.02f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [1.1124f,0f,-0.0052f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,0f]