#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [7.5572f,13.9013f,-11.5674f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [8.3757f,16.0616f,-13.1814f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [9.0559f,14.1949f,-10.3324f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [8.999f,10.5281f,-6.4052f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [8.7286f,5.5626f,-2.0033f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [8.7467f,-0.1453f,2.4484f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [9.3227f,-5.9098f,6.5476f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [10.4018f,-10.984f,9.9452f]