#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [11.5233f,-14.6601f,12.7326f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [12.9299f,-16.3673f,15.6923f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [15.2469f,-16.168f,18.1447f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [18.7764f,-14.8502f,19.6487f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [23.4696f,-12.9712f,19.7092f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [28.9584f,-10.6874f,17.9325f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [34.624f,-7.6943f,14.1277f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [39.7082f,-3.3675f,8.3452f]