#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.602 ^0.684 ^0.877 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.592 ^0.739 ^0.795 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.582 ^0.79 ^0.711 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.571 ^0.837 ^0.625 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.561 ^0.88 ^0.541 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.551 ^0.918 ^0.457 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.541 ^0.951 ^0.376 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.532 ^0.98 ^0.298 ~ ~