#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [23.9431f,0f,-0.3931f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [21.4553f,0f,-0.3579f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [18.986f,0f,-0.3185f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [16.5567f,0f,-0.2764f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [14.1885f,0f,-0.233f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [11.9028f,0f,-0.1895f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [9.7209f,0f,-0.1474f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [7.6639f,0f,-0.1081f]