#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.666 ^-0.08 ^0.776 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.676 ^-0.055 ^0.745 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.685 ^-0.029 ^0.71 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.694 ^-0.002 ^0.672 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.704 ^0.025 ^0.631 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.713 ^0.053 ^0.587 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.722 ^0.08 ^0.541 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.73 ^0.107 ^0.493 ~ ~