#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [44.7054f,0f,6.349f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [45.2926f,0f,6.2286f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [46.0549f,0f,5.9234f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [46.9206f,0f,5.4665f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [47.8176f,0f,4.8912f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [48.6741f,0f,4.2305f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [49.4184f,0f,3.5176f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [49.9784f,0f,2.7856f]