#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-0.688 ^0.375 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-0.69 ^0.385 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-0.692 ^0.393 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-0.694 ^0.401 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-0.696 ^0.408 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-0.698 ^0.414 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-0.7 ^0.419 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-0.701 ^0.423 ~ ~