#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0 ^-0.699 ^0.4 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0 ^-0.697 ^0.394 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0 ^-0.694 ^0.388 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0 ^-0.691 ^0.382 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0 ^-0.688 ^0.375 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0 ^-0.684 ^0.366 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0 ^-0.678 ^0.356 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0 ^-0.672 ^0.344 ~ ~