#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [32.5f,0f,-7.5f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [37.1427f,0f,-6.1836f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [38.7536f,0f,-3.5042f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [38.648f,0f,-0.4321f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [38.141f,0f,2.0624f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [38.5004f,0f,3.0116f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [39.1955f,0f,1.9986f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [39.709f,0f,-0.173f]