#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-0.708 ^0.431 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-0.707 ^0.429 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-0.707 ^0.426 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^-0.706 ^0.422 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^-0.705 ^0.419 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^-0.704 ^0.415 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^-0.703 ^0.41 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^-0.701 ^0.405 ~ ~