#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-0.56 ^-0.193 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^-0.566 ^-0.182 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^-0.582 ^-0.131 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^-0.601 ^-0.053 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.621 ^0.042 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-0.642 ^0.143 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-0.661 ^0.239 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-0.677 ^0.32 ~ ~