#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0 ^-0.665 ^0.33 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0 ^-0.658 ^0.315 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0 ^-0.65 ^0.299 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0 ^-0.641 ^0.282 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0 ^-0.632 ^0.264 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0 ^-0.623 ^0.245 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0 ^-0.614 ^0.226 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0 ^-0.604 ^0.207 ~ ~