#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [8.5294f,-16.5552f,23.8267f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [10.0796f,-18.2303f,25.2561f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [13.6522f,-17.5251f,23.6431f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [18.7089f,-14.9363f,19.9114f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [24.4574f,-10.8937f,14.935f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [30.1848f,-5.9228f,9.4644f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [35.3589f,-0.6584f,4.0816f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [39.6425f,4.193f,-0.744f]