#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.007 ^-0.497 ^1.148 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.005 ^-0.484 ^1.138 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.003 ^-0.465 ^1.126 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.001 ^-0.439 ^1.112 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0 ^-0.406 ^1.093 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.001 ^-0.376 ^1.074 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.001 ^-0.343 ^1.05 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.002 ^-0.307 ^1.022 ~ ~