#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.001 ^0.173 ^-0.547 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.002 ^0.174 ^-0.512 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.014 ^0.185 ^-0.356 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.032 ^0.182 ^-0.115 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.051 ^0.142 ^0.173 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.064 ^0.054 ^0.47 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.067 ^-0.071 ^0.733 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.061 ^-0.206 ^0.935 ~ ~