#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.022 ^-0.51 ^1.194 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.022 ^-0.507 ^1.188 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.022 ^-0.499 ^1.18 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.019 ^-0.503 ^1.177 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.017 ^-0.507 ^1.173 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.014 ^-0.509 ^1.169 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.012 ^-0.509 ^1.163 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.01 ^-0.505 ^1.156 ~ ~