#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [5.2168f,14.9209f,-20.9509f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [4.7824f,17.4389f,-25.6039f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [5.7939f,15.7829f,-22.8962f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [7.1043f,11.8812f,-16.1326f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [8.2022f,6.3156f,-7.0868f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [8.7459f,-0.1861f,2.7134f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [8.7263f,-6.7629f,11.9477f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [8.4856f,-12.5164f,19.3338f]