#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.005 ^0.065 ^0.609 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.004 ^0.101 ^0.55 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.004 ^0.134 ^0.491 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.004 ^0.165 ^0.431 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.003 ^0.192 ^0.372 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.003 ^0.217 ^0.314 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.002 ^0.238 ^0.258 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.001 ^0.257 ^0.204 ~ ~