#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.012 ^-0.432 ^1.164 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.019 ^-0.435 ^1.167 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.019 ^-0.439 ^1.169 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.011 ^-0.444 ^1.172 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.001 ^-0.452 ^1.175 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.011 ^-0.465 ^1.18 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.019 ^-0.484 ^1.187 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.022 ^-0.502 ^1.193 ~ ~