#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.319 ^0.376 ^1.533 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.324 ^0.43 ^1.478 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.331 ^0.487 ^1.415 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.338 ^0.544 ^1.346 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.347 ^0.601 ^1.272 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.357 ^0.657 ^1.192 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.367 ^0.711 ^1.108 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.378 ^0.762 ^1.02 ~ ~