#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.387 ^0.085 ^1.722 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.344 ^0.093 ^1.742 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.331 ^0.116 ^1.733 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.321 ^0.15 ^1.714 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.315 ^0.196 ^1.686 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.313 ^0.233 ^1.659 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.313 ^0.276 ^1.624 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.315 ^0.324 ^1.582 ~ ~