#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.015 ^0.584 ^1.146 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.163 ^0.488 ^1.24 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.446 ^0.359 ^1.205 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.666 ^0.189 ^1.101 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.755 ^0.085 ^1.042 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.731 ^0.128 ^1.099 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.596 ^0.258 ^1.21 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.372 ^0.379 ^1.307 ~ ~