#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-6.4027f,13.2316f,-45.2778f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0.5243f,10.8686f,-35.5168f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [6.1618f,1.1847f,-18.6514f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [7.6484f,-9.5495f,-2.1154f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [6.5184f,-14.5725f,8.5555f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [6.2627f,-11.4216f,9.2702f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [6.7582f,-3.309f,3.1215f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [7.0561f,6.3864f,-5.4685f]