#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-18.3422f,0.3295f,1.7516f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-21.4509f,0.4572f,2.0672f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-24.6274f,0.6044f,2.3665f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-27.8381f,0.7664f,2.639f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-31.0491f,0.9372f,2.875f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-34.2268f,1.1088f,3.0661f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-37.3377f,1.2725f,3.2046f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-40.3482f,1.4184f,3.2844f]