#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.156 ^0.432 ^1.359 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.071 ^0.437 ^1.376 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.115 ^0.427 ^1.378 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.233 ^0.401 ^1.365 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.389 ^0.345 ^1.336 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.546 ^0.251 ^1.292 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.671 ^0.135 ^1.241 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.751 ^0.028 ^1.193 ~ ~