#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.729 ^0.143 ^0.444 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.738 ^0.167 ^0.394 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.746 ^0.189 ^0.344 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.755 ^0.209 ^0.294 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.763 ^0.228 ^0.244 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.771 ^0.244 ^0.196 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.779 ^0.259 ^0.149 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.786 ^0.272 ^0.105 ~ ~