#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [34.2168f,12.4182f,-9.6173f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [30.6318f,10.7405f,-9.0754f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [27.098f,9.1552f,-8.4159f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [23.6376f,7.6775f,-7.6555f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [20.2737f,6.3193f,-6.8137f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [17.031f,5.0887f,-5.9126f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [13.9355f,3.9902f,-4.9757f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [11.0141f,3.0244f,-4.028f]