#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.438 ^-0.341 ^-0.021 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.437 ^-0.347 ^-0.006 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.434 ^-0.372 ^0.063 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.43 ^-0.409 ^0.166 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.428 ^-0.458 ^0.287 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.427 ^-0.513 ^0.408 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.43 ^-0.569 ^0.515 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.434 ^-0.62 ^0.599 ~ ~