#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [62.247f,26.6858f,-8.9349f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [59.0176f,25.0284f,-9.4773f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [55.658f,23.2916f,-9.9122f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [52.1973f,21.4956f,-10.2218f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [48.6619f,19.6624f,-10.3936f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [45.0751f,17.815f,-10.4197f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [41.4585f,15.9766f,-10.2973f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [37.8325f,14.1703f,-10.0278f]