#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [92.6849f,38.2192f,10.5862f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [91.5311f,38.0607f,9.735f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [90.381f,37.9571f,8.5434f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [88.8436f,38.0239f,6.7129f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [87.8292f,38.2138f,5.0251f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [87.0495f,38.3824f,3.4472f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [86.2202f,38.3784f,1.9413f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [85.0617f,38.0466f,0.4685f]