#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.805 ^0.305 ^-0.076 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.795 ^0.295 ^-0.093 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.784 ^0.284 ^-0.114 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.772 ^0.271 ^-0.138 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.758 ^0.256 ^-0.165 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.744 ^0.24 ^-0.193 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.729 ^0.223 ^-0.222 ~ ~