#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [83.3071f,37.2283f,-1.0002f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [80.7155f,35.7608f,-2.4653f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [78.0144f,34.1885f,-3.7579f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [75.9187f,33.2847f,-4.9284f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [73.142f,32.1903f,-6.2024f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [70.8029f,31.0099f,-6.9088f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [68.1785f,29.6912f,-7.6217f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [65.3129f,28.2454f,-8.3074f]