#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.389 ^0.809 ^0.929 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.401 ^0.853 ^0.837 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.413 ^0.892 ^0.744 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.424 ^0.927 ^0.651 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.436 ^0.957 ^0.559 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.447 ^0.982 ^0.47 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.458 ^1.004 ^0.384 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.467 ^1.021 ^0.303 ~ ~