#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-57.3521f,0.3799f,0.6176f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-57.3921f,-0.3195f,-0.6005f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-53.9047f,-2.4268f,-5.5361f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-46.4767f,-4.0821f,-13.2653f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-36.7686f,-3.672f,-22.7045f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-26.7456f,-0.5431f,-32.1017f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-17.9956f,4.5589f,-39.6931f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-11.2002f,9.8548f,-44.3012f]