#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.507 ^0.573 ^-1.177 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.493 ^0.583 ^-1.145 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.434 ^0.665 ^-0.973 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.342 ^0.781 ^-0.676 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.228 ^0.868 ^-0.282 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.113 ^0.881 ^0.158 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.022 ^0.812 ^0.581 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.024 ^0.695 ^0.924 ~ ~