#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.615 ^-0.222 ^0.902 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.616 ^-0.211 ^0.899 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.619 ^-0.196 ^0.892 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.623 ^-0.177 ^0.88 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.628 ^-0.155 ^0.864 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.635 ^-0.138 ^0.848 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.642 ^-0.118 ^0.828 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.65 ^-0.095 ^0.804 ~ ~