#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-5.9202f,0.0488f,0.8995f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-13.7772f,0.198f,2.1606f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-23.2477f,0.4534f,3.7096f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-34.0065f,0.819f,5.4721f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-45.7272f,1.2948f,7.3737f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-58.0827f,1.8739f,9.341f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-70.7464f,2.541f,11.3022f]