#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-21.2061f,0f,0.5539f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-22.3857f,0f,0.5542f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-23.4214f,0f,0.5417f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-24.2919f,0f,0.5148f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-24.9761f,0f,0.472f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-25.4529f,0f,0.412f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-25.7011f,0f,0.3332f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-25.6995f,0f,0.2341f]