#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.437 ^-0.578 ^0.467 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.437 ^-0.557 ^0.446 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.437 ^-0.536 ^0.426 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.437 ^-0.515 ^0.405 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.437 ^-0.494 ^0.384 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.437 ^-0.475 ^0.364 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.437 ^-0.456 ^0.344 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.437 ^-0.439 ^0.325 ~ ~