#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-110.3322f,-19.3427f,3.0257f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-97.6339f,-18.2694f,-0.5029f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-63.592f,-9.2101f,-8.4775f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-21.0958f,6.6804f,-14.666f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [22.5946f,24.7352f,-15.7667f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [62.5499f,39.231f,-10.4572f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [88.4057f,44.222f,-1.9571f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [102.6721f,43.8261f,5.4601f]