#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-43.2248f,1.5362f,3.3002f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-45.9339f,1.6155f,3.2479f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-48.4419f,1.646f,3.1237f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-50.7147f,1.6185f,2.9241f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-52.7184f,1.5245f,2.6454f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-54.4187f,1.3573f,2.2827f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-55.781f,1.112f,1.83f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-56.7705f,0.7861f,1.2787f]