#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.517 ^-0.12 ^0.817 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.5 ^-0.11 ^0.824 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.501 ^-0.116 ^0.832 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.517 ^-0.135 ^0.839 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.541 ^-0.162 ^0.845 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.567 ^-0.193 ^0.852 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.59 ^-0.22 ^0.858 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.604 ^-0.239 ^0.864 ~ ~