#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.369 ^-1 ^0 ~ ~