#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.567 ^-0.168 ^0.817 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.58 ^-0.188 ^0.824 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.579 ^-0.193 ^0.832 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.565 ^-0.183 ^0.839 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.544 ^-0.165 ^0.845 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.52 ^-0.145 ^0.852 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.5 ^-0.129 ^0.858 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.489 ^-0.12 ^0.864 ~ ~