#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.633 ^-0.153 ^0.691 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.616 ^-0.169 ^0.749 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.588 ^-0.154 ^0.773 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.556 ^-0.125 ^0.779 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.528 ^-0.101 ^0.781 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.516 ^-0.097 ^0.79 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.525 ^-0.114 ^0.801 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.545 ^-0.14 ^0.81 ~ ~