#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-5.698f,-0.0181f,-0.905f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-13.2467f,-0.0854f,-2.1808f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-22.3387f,-0.2227f,-3.7517f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-32.6649f,-0.4494f,-5.5404f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-43.9143f,-0.78f,-7.4691f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-55.7756f,-1.2216f,-9.4595f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-67.9378f,-1.7722f,-11.4335f]