#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.088 ^0.35 ^1.443 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.055 ^0.346 ^1.469 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.074 ^0.339 ^1.499 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.135 ^0.308 ^1.538 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.225 ^0.264 ^1.573 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.331 ^0.206 ^1.595 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.438 ^0.136 ^1.603 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.532 ^0.065 ^1.597 ~ ~