#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.6082f,0f,0.0059f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-1.4107f,0f,0.0224f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-2.3864f,0f,0.0482f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-3.5141f,0f,0.0818f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-4.7726f,0f,0.1217f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-6.1408f,0f,0.1664f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-7.5976f,0f,0.2144f]