#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [112.379f,-40.2146f,-13.0221f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [110.0433f,-40.1644f,-14.6563f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [107.7012f,-40.0696f,-14.6538f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [105.3376f,-39.9498f,-13.145f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [103.0475f,-39.8093f,-10.7716f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [100.8839f,-39.6579f,-8.1181f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [98.9001f,-39.5055f,-5.7698f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [97.1499f,-39.3614f,-4.3124f]