#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function warden:animations/animation.warden.roar/tree/right_arm_display_64-71
execute if score .this aj.frame matches 72..79 run function warden:animations/animation.warden.roar/tree/right_arm_display_72-79
execute if score .this aj.frame matches 80..85 run function warden:animations/animation.warden.roar/tree/right_arm_display_80-85