#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.747 ^0.087 ^1.102 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.789 ^0.025 ^1.077 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.771 ^0.053 ^1.106 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.707 ^0.129 ^1.159 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.597 ^0.222 ^1.226 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.453 ^0.299 ^1.296 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.3 ^0.341 ^1.359 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.17 ^0.352 ^1.409 ~ ~