#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.805 ^0.305 ^-0.076 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.795 ^0.296 ^-0.093 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.783 ^0.285 ^-0.114 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.769 ^0.273 ^-0.138 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.755 ^0.259 ^-0.165 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.739 ^0.244 ^-0.193 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.723 ^0.228 ^-0.222 ~ ~