#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.492 ^-0.12 ^0.867 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.498 ^-0.123 ^0.872 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.507 ^-0.129 ^0.878 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.516 ^-0.137 ^0.884 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.527 ^-0.147 ^0.89 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.539 ^-0.157 ^0.895 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.552 ^-0.166 ^0.9 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.565 ^-0.174 ^0.902 ~ ~