#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.794 ^0.281 ^0.063 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.8 ^0.291 ^0.026 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.804 ^0.3 ^-0.008 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.809 ^0.307 ^-0.038 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~