#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [37.5624f,15.1217f,-18.449f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [36.1308f,14.156f,-18.3663f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [34.548f,13.0633f,-18.1278f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [32.8278f,11.8769f,-17.7321f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [30.9835f,10.6306f,-17.1802f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [29.0283f,9.3576f,-16.4764f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [26.9761f,8.0899f,-15.6283f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [24.8423f,6.8575f,-14.6471f]