#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.444 ^-0.746 ^0.696 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.445 ^-0.749 ^0.693 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.445 ^-0.755 ^0.689 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.445 ^-0.761 ^0.685 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.445 ^-0.769 ^0.679 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.444 ^-0.777 ^0.674 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.443 ^-0.784 ^0.668 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.442 ^-0.791 ^0.661 ~ ~