#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.438 ^-0.584 ^0.467 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.438 ^-0.562 ^0.446 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.438 ^-0.54 ^0.426 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.438 ^-0.519 ^0.405 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.438 ^-0.498 ^0.384 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.438 ^-0.478 ^0.364 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.438 ^-0.459 ^0.344 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.438 ^-0.441 ^0.325 ~ ~