#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.437 ^-0.339 ^-0.021 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.438 ^-0.349 ^-0.006 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.441 ^-0.388 ^0.063 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.444 ^-0.445 ^0.166 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.445 ^-0.516 ^0.287 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.444 ^-0.593 ^0.408 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.439 ^-0.669 ^0.515 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.434 ^-0.732 ^0.599 ~ ~