#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [5.4841f,0.3151f,-3.2735f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [3.7961f,0.1485f,-2.2178f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [2.3022f,0.0534f,-1.3044f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [1.0285f,0.0103f,-0.5576f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,0f]