#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-43.2314f,1.2833f,3.0311f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-45.9406f,1.35f,2.9908f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-48.4482f,1.3758f,2.884f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-50.7204f,1.3528f,2.7067f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-52.7231f,1.2741f,2.4547f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-54.4222f,1.134f,2.1229f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-55.7832f,0.9284f,1.7051f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-56.7715f,0.6555f,1.1932f]