#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-109.6889f,9.9189f,9.99f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-97.0856f,9.1912f,13.1021f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-62.9381f,2.8888f,17.4107f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-19.251f,-8.1167f,18.986f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [26.0451f,-20.8499f,16.4673f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [65.956f,-31.8234f,9.7638f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [89.9196f,-37.2338f,1.2292f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [103.0391f,-38.6695f,-6.4392f]