#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.warden.anim.animation.warden.emerge
tag @s remove aj.warden.anim.animation.warden.dig
tag @s remove aj.warden.anim.animation.warden.roar
tag @s remove aj.warden.anim.animation.warden.sniff
tag @s remove aj.warden.anim.animation.warden.attack
tag @s remove aj.warden.anim.animation.warden.hurt
tag @s remove aj.warden.anim.animation.warden.sonic_boom
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.warden.bone,distance=..5.96] if score @s aj.id = .this aj.id run function warden:zzz/execute/5
execute as @e[type=minecraft:armor_stand,tag=aj.warden.bone,distance=..5.96] if score @s aj.id = .this aj.id run function warden:zzz/execute/6
scoreboard players set #execute aj.i 1