#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
scoreboard players set # aj.i 0
execute if entity @s[tag=aj.warden.anim.animation.warden.emerge] run function warden:zzz/execute/7
execute if entity @s[tag=aj.warden.anim.animation.warden.dig] run function warden:zzz/execute/10
execute if entity @s[tag=aj.warden.anim.animation.warden.roar] run function warden:zzz/execute/13
execute if entity @s[tag=aj.warden.anim.animation.warden.sniff] run function warden:zzz/execute/16
execute if entity @s[tag=aj.warden.anim.animation.warden.attack] run function warden:zzz/execute/19
execute if entity @s[tag=aj.warden.anim.animation.warden.hurt] run function warden:zzz/execute/22
execute if entity @s[tag=aj.warden.anim.animation.warden.sonic_boom] run function warden:zzz/execute/25
execute if score # aj.i matches 0 run function warden:zzz/execute/28
scoreboard players set #execute aj.i 1