#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.565 ^0.115 ^-0.642 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.66 ^0.24 ^-0.333 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.788 ^0.269 ^0.13 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.829 ^0.208 ^0.385 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.828 ^0.233 ^0.323 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.817 ^0.298 ^0.061 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~