#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0.0221f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [1.8188f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [3.2981f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0.0687f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-11.0153f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-7.7251f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,0f,0f]