#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.warden.animation.warden.hurt.loopMode matches 0 run function warden:animations/animation.warden.hurt/stop
execute if score @s aj.warden.animation.warden.hurt.loopMode matches 1 run function warden:animations/animation.warden.hurt/pause
execute if score @s aj.warden.animation.warden.hurt.loopMode matches 2 run function warden:animations/animation.warden.hurt/zzz/execute/36