#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#warden:bone_entities,tag=aj.warden.bone] if score @s aj.id = .this aj.id run function warden:zzz/execute/23