#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.warden.animation.warden.roar.loopMode matches 0 run function warden:animations/animation.warden.roar/stop
execute if score @s aj.warden.animation.warden.roar.loopMode matches 1 run function warden:animations/animation.warden.roar/pause
execute if score @s aj.warden.animation.warden.roar.loopMode matches 2 run function warden:animations/animation.warden.roar/zzz/execute/33