#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.warden.animation.warden.sniff.loopMode matches 0 run function warden:animations/animation.warden.sniff/stop
execute if score @s aj.warden.animation.warden.sniff.loopMode matches 1 run function warden:animations/animation.warden.sniff/pause
execute if score @s aj.warden.animation.warden.sniff.loopMode matches 2 run function warden:animations/animation.warden.sniff/zzz/execute/34