#Project generated by Animated Java (https://animated-java.dev/)

schedule function warden:animation_loop 1t
scoreboard players set .aj.anim_loop aj.warden.animating 1
scoreboard players set .aj.animation aj.warden.animating 0
execute as @e[type=minecraft:marker,tag=aj.warden.root] run function warden:zzz/execute/29
execute if score .aj.animation aj.warden.animating matches 0 run function warden:zzz/execute/30