#Project generated by Animated Java (https://animated-java.dev/)

scoreboard objectives add aj.i dummy
scoreboard objectives add aj.id dummy
scoreboard objectives add aj.frame dummy
scoreboard objectives add aj.warden.animating dummy
scoreboard objectives add aj.warden.animation.warden.emerge.loopMode dummy
scoreboard objectives add aj.warden.animation.warden.dig.loopMode dummy
scoreboard objectives add aj.warden.animation.warden.roar.loopMode dummy
scoreboard objectives add aj.warden.animation.warden.sniff.loopMode dummy
scoreboard objectives add aj.warden.animation.warden.attack.loopMode dummy
scoreboard objectives add aj.warden.animation.warden.hurt.loopMode dummy
scoreboard objectives add aj.warden.animation.warden.sonic_boom.loopMode dummy
function warden:reset_animation_flags
scoreboard players set #uninstall aj.i 0
scoreboard players set .aj.warden.framerate aj.i 1
tellraw @a [{"text":"[ ","color":"dark_gray"},{"text":"AJ","color":"aqua"},{"text":" → ","color":"gray"},{"text":"Install ⊻","color":"green"},{"text":" ]","color":"dark_gray"},"\n",{"text":"Installed ","color":"gray"},{"text":"armor_stand","color":"gold"},{"text":" rig.","color":"gray"},"\n",{"text":"◘ ","color":"gray"},{"text":"Included Scoreboard Objectives:","color":"green"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.i","color":"aqua"},{"text":" (Internal)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.id","color":"aqua"},{"text":" (ID)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.frame","color":"aqua"},{"text":" (Frame)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animating","color":"aqua"},{"text":" (Animation Flag)","color":"dark_gray"},[["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animation.warden.emerge.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}],["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animation.warden.dig.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}],["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animation.warden.roar.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}],["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animation.warden.sniff.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}],["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animation.warden.attack.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}],["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animation.warden.hurt.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}],["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.warden.animation.warden.sonic_boom.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}]]]