#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.warden.root] at @s run function warden:animations/animation.warden.attack/zzz/conditional/46
execute if score #execute aj.i matches 0 run function warden:animations/animation.warden.attack/zzz/conditional/47