#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.5 ^1.051 ^-0.135 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.5 ^1.01 ^-0.285 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.5 ^1.01 ^-0.285 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.5 ^1.051 ^-0.135 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.5 ^1.062 ^0 ~ ~