#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.813 ^0.29 ^-0.196 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.813 ^0.239 ^-0.343 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.813 ^0.239 ^-0.343 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.813 ^0.29 ^-0.196 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~