#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0 ^-1.874 ^0.345 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0 ^-1.917 ^0.35 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0 ^-2.003 ^0.362 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0 ^-2.117 ^0.377 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0 ^-2.25 ^0.396 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0 ^-2.395 ^0.416 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0 ^-2.543 ^0.436 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0 ^-2.686 ^0.456 ~ ~