#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0 ^-1.792 ^0.336 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0 ^-1.799 ^0.336 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0 ^-1.805 ^0.336 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0 ^-1.81 ^0.337 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0 ^-1.814 ^0.339 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0 ^-1.819 ^0.34 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0 ^-1.822 ^0.342 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0 ^-1.826 ^0.343 ~ ~