#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-1.381 ^0.452 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-1.366 ^0.434 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-1.349 ^0.406 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-1.33 ^0.37 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-1.31 ^0.327 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-1.29 ^0.281 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-1.271 ^0.233 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-1.253 ^0.185 ~ ~