#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.374 ^0.349 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.465 ^0.385 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.531 ^0.411 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.602 ^0.439 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.596 ^0.436 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.558 ^0.42 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.531 ^0.411 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.535 ^0.414 ~ ~