#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0 ^-1.829 ^0.345 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0 ^-1.833 ^0.346 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0 ^-1.837 ^0.348 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0 ^-1.841 ^0.348 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0 ^-1.845 ^0.349 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0 ^-1.845 ^0.348 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0 ^-1.841 ^0.347 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0 ^-1.834 ^0.346 ~ ~