#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.037 ^-0.92 ^0.912 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.015 ^-1.299 ^1.119 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.001 ^-1.643 ^1.179 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.004 ^-1.908 ^1.148 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.07 ^-2.086 ^1.088 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.091 ^-2.101 ^1.072 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.071 ^-2.138 ^1.061 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.006 ^-2.165 ^1.054 ~ ~