#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.312 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.003 ^0.246 ^0.025 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.008 ^0.155 ^0.053 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.013 ^0.046 ^0.096 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.016 ^-0.076 ^0.163 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.017 ^-0.205 ^0.264 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.017 ^-0.347 ^0.416 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.016 ^-0.509 ^0.602 ~ ~