#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-140.0374f,-0.3381f,0.2724f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [-141.7795f,0.6412f,-0.6534f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [-144.6241f,2.8141f,-2.8828f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [-148.0866f,5.4787f,-5.6138f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [-151.5968f,7.7999f,-7.9727f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [-154.5841f,8.9426f,-9.0856f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [-156.8642f,7.3155f,-7.246f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [-158.2951f,0.9427f,-0.331f]