#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [12.1484f,3.6702f,-10.8599f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-2.1584f,2.5421f,-7.5219f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-14.5719f,1.529f,-4.5242f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-24.2376f,0.6878f,-2.0352f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-30.3012f,0.0755f,-0.2234f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-27.6939f,-0.516f,1.5909f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-14.1092f,-0.8665f,2.8206f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [7.3445f,-0.9716f,3.3611f]