#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.012 ^-0.69 ^0.787 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.004 ^-0.869 ^0.937 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.009 ^1.034 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.009 ^-1.122 ^1.095 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.022 ^-1.122 ^1.095 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.03 ^-1.07 ^1.069 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.009 ^-1.033 ^1.053 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.042 ^-1.042 ^1.059 ~ ~