#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.109 ^-2.471 ^0.832 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.188 ^-2.464 ^0.822 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.153 ^-2.49 ^0.805 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.038 ^-2.52 ^0.792 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.008 ^-2.53 ^0.786 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.014 ^-2.533 ^0.78 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.01 ^-2.532 ^0.774 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.003 ^-2.526 ^0.772 ~ ~