#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.84 ^-0.159 ^0.432 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.824 ^-0.223 ^0.666 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.795 ^-0.281 ^0.831 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.699 ^-0.333 ^0.933 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.572 ^-0.343 ^0.945 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.493 ^-0.353 ^0.921 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.519 ^-0.393 ^0.91 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.627 ^-0.471 ^0.915 ~ ~