#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [-158.9396f,-5.8696f,7.0223f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [-159.2779f,-8.286f,9.6262f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [-159.575f,-5.3128f,6.422f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [-159.6275f,0.1964f,0.4756f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [-159.1715f,5.7387f,-5.5274f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [-157.9429f,8.8111f,-8.9017f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [-155.9213f,8.5707f,-8.7395f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [-153.0239f,6.7344f,-6.8944f]