#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.694 ^-1.509 ^1.935 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.598 ^-1.525 ^1.979 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.532 ^-1.537 ^2.002 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.485 ^-1.515 ^2.013 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.431 ^-1.452 ^2.02 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.359 ^-1.362 ^2.022 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.269 ^-1.255 ^2.013 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.166 ^-1.132 ^1.988 ~ ~