#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.436 ^-2.067 ^0.196 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.442 ^-2.056 ^0.207 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.455 ^-2.037 ^0.233 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.469 ^-2.017 ^0.266 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.479 ^-2.004 ^0.297 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.482 ^-2.004 ^0.317 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.474 ^-2.034 ^0.314 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.44 ^-2.111 ^0.272 ~ ~