#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.506 ^0.994 ^0.032 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.515 ^0.901 ^0.066 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.524 ^0.788 ^0.121 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.531 ^0.663 ^0.22 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.531 ^0.525 ^0.383 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.531 ^0.359 ^0.642 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.528 ^0.137 ^0.967 ~ ~