#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.815 ^0.263 ^-0.077 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.82 ^0.194 ^-0.105 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.827 ^0.112 ^-0.131 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.833 ^0.031 ^-0.138 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.836 ^-0.037 ^-0.107 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.839 ^-0.08 ^0.001 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.844 ^-0.113 ^0.193 ~ ~