#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [114.9947f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [115.0144f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [115.0417f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [115.0761f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [115.1171f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [115.1641f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [115.2166f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [115.2741f,0f,0f]