#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.43 ^-1.418 ^0.637 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.431 ^-1.553 ^0.661 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.438 ^-1.642 ^0.668 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.458 ^-1.692 ^0.666 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.48 ^-1.629 ^0.63 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.492 ^-1.536 ^0.583 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.499 ^-1.499 ^0.551 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.502 ^-1.544 ^0.546 ~ ~