#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [82.7642f,20.1463f,-22.1593f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [108.7858f,22.0724f,-27.3012f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [116.6988f,22.4714f,-29.5662f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [107.7061f,22.2754f,-29.6944f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [82.6779f,20.9445f,-28.4527f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [49.4593f,18.0852f,-26.3883f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [18.5706f,14.8786f,-23.5583f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-18.0324f,11.4719f,-19.5778f]