#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [116.5912f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [116.5108f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [116.4172f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [116.3101f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [116.1887f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [116.0527f,0f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [115.9015f,0f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [115.7346f,0f,0f]