#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.243 ^-3.151 ^0.356 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.053 ^-3.176 ^0.324 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.149 ^-3.173 ^0.3 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.418 ^-3.12 ^0.298 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.517 ^-3.09 ^0.295 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.525 ^-3.088 ^0.287 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.514 ^-3.091 ^0.278 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.499 ^-3.094 ^0.277 ~ ~