#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [99.7396f,9.9087f,-29.3317f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [95.5268f,10.0022f,-29.5963f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [90.3883f,9.6639f,-28.5954f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [82.1774f,9.042f,-26.755f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [71.2203f,8.1933f,-24.2437f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [57.8844f,7.1748f,-21.23f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [43.0242f,6.0435f,-17.8825f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [27.4941f,4.8563f,-14.3696f]