#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.799 ^-2.351 ^1.038 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.796 ^-2.313 ^1.061 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.785 ^-2.246 ^1.11 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.764 ^-2.168 ^1.167 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.737 ^-2.101 ^1.217 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.718 ^-2.06 ^1.248 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.731 ^-2.065 ^1.24 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.793 ^-2.156 ^1.166 ~ ~