#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.391 ^-2.193 ^0.225 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.371 ^-2.253 ^0.213 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.396 ^-2.318 ^0.247 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.436 ^-2.389 ^0.303 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.467 ^-2.474 ^0.361 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.481 ^-2.589 ^0.398 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0.482 ^-2.735 ^0.407 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0.475 ^-2.888 ^0.4 ~ ~