#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.709 ^-2.444 ^1.05 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.631 ^-2.56 ^1.02 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.668 ^-2.532 ^1.02 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.765 ^-2.4 ^1.045 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.797 ^-2.351 ^1.053 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.803 ^-2.351 ^1.047 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.804 ^-2.358 ^1.038 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.802 ^-2.362 ^1.033 ~ ~