#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.369 ^-1.918 ^0.139 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.369 ^-1.918 ^0.139 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.369 ^-1.918 ^0.139 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.369 ^-1.917 ^0.139 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.369 ^-1.917 ^0.139 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.369 ^-1.916 ^0.14 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.369 ^-1.915 ^0.14 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.369 ^-1.914 ^0.14 ~ ~