#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.349 ^-1.881 ^0.604 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.389 ^-1.821 ^0.608 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.422 ^-1.754 ^0.618 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.443 ^-1.688 ^0.637 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.457 ^-1.613 ^0.663 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.461 ^-1.531 ^0.693 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.453 ^-1.449 ^0.724 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.434 ^-1.376 ^0.749 ~ ~