#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.757 ^-2.133 ^1.153 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.733 ^-2.229 ^1.135 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.758 ^-2.157 ^1.151 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.788 ^-2.022 ^1.174 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.8 ^-1.909 ^1.186 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.814 ^-1.897 ^1.178 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.829 ^-2.025 ^1.145 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.798 ^-2.238 ^1.098 ~ ~