#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.369 ^-1.912 ^0.14 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.369 ^-1.911 ^0.141 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.369 ^-1.909 ^0.141 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.369 ^-1.906 ^0.141 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.369 ^-1.903 ^0.142 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.369 ^-1.9 ^0.142 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.369 ^-1.897 ^0.143 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.369 ^-1.893 ^0.144 ~ ~