#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.494 ^-3.091 ^0.292 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.515 ^-3.079 ^0.332 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.56 ^-3.054 ^0.408 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.608 ^-3.022 ^0.501 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.64 ^-2.993 ^0.592 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.648 ^-2.98 ^0.662 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.612 ^-3.005 ^0.696 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.502 ^-3.086 ^0.672 ~ ~