#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [116.5161f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [116.5752f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [116.6294f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [116.6783f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [116.7213f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [116.758f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [116.7877f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [116.81f,0f,0f]