#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.369 ^-1.876 ^0.147 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.369 ^-1.877 ^0.147 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.369 ^-1.878 ^0.147 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.369 ^-1.878 ^0.146 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.369 ^-1.879 ^0.146 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.369 ^-1.88 ^0.146 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.369 ^-1.881 ^0.146 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.369 ^-1.883 ^0.146 ~ ~