#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.369 ^-1.759 ^0.234 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.369 ^-1.883 ^0.232 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.369 ^-2.026 ^0.238 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.369 ^-2.228 ^0.256 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.369 ^-2.447 ^0.279 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.369 ^-2.64 ^0.3 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0.369 ^-2.75 ^0.313 ~ ~