#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.347 ^-2.176 ^0.295 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.322 ^-2.202 ^0.276 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.388 ^-2.144 ^0.273 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.466 ^-2.03 ^0.276 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.506 ^-1.912 ^0.279 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.512 ^-1.871 ^0.273 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.498 ^-1.938 ^0.253 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.45 ^-2.056 ^0.226 ~ ~