#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [115.9317f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [116.0108f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [116.0892f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [116.1664f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [116.2419f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [116.3151f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [116.3855f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [116.4527f,0f,0f]