#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.934 ^-1.482 ^1.345 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.856 ^-1.392 ^1.39 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.779 ^-1.292 ^1.412 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.703 ^-1.178 ^1.413 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.606 ^-1.041 ^1.398 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.485 ^-0.898 ^1.366 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.353 ^-0.764 ^1.311 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.231 ^-0.648 ^1.229 ~ ~