#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [115.3361f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [115.4021f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [115.4716f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [115.5439f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [115.6187f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [115.6954f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [115.7735f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [115.8524f,0f,0f]