#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [7.3587f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [17.477f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [29.6648f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [43.2325f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [57.49f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [71.7475f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [85.3152f,0f,0f]