#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.84 ^-2.291 ^1.071 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.851 ^-2.378 ^1.038 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.839 ^-2.411 ^1.096 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.803 ^-2.439 ^1.192 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.753 ^-2.504 ^1.28 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.724 ^-2.631 ^1.33 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0.734 ^-2.809 ^1.334 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0.761 ^-3.011 ^1.312 ~ ~