#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.441 ^-1.489 ^0.494 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.445 ^-1.642 ^0.49 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.443 ^-1.75 ^0.459 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.432 ^-1.837 ^0.419 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.357 ^-2.029 ^0.352 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.281 ^-2.179 ^0.309 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.324 ^-2.179 ^0.306 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.431 ^-2.073 ^0.328 ~ ~