#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [22.6707f,4.1372f,-4.2402f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [25.5399f,1.614f,-1.6508f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [27.5f,0f,0f]