#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.481 ^-0.103 ^1.261 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.495 ^-0.392 ^1.517 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.5 ^-0.633 ^1.683 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.5 ^-0.843 ^1.797 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.491 ^-0.915 ^1.836 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.468 ^-0.899 ^1.838 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.413 ^-0.862 ^1.84 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.335 ^-0.846 ^1.854 ~ ~