#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.dig/tree/right_arm_display_0-63
execute if score .this aj.frame matches 64..101 run function warden:animations/animation.warden.dig/tree/right_arm_display_64-101