#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-168.12f,-3.2743f,15.3112f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-164.6948f,-4.0031f,18.7736f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-160.2523f,-1.9271f,8.9219f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-155.189f,1.3033f,-6.4087f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-150.4534f,4.149f,-19.9129f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-146.9818f,5.0766f,-24.3155f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-144.8657f,3.4846f,-16.7663f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-143.571f,0.5262f,-2.7351f]