#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.369 ^-1.901 ^0.146 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.369 ^-1.902 ^0.146 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.369 ^-1.903 ^0.146 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.369 ^-1.904 ^0.145 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.369 ^-1.905 ^0.145 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.369 ^-1.905 ^0.145 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.369 ^-1.906 ^0.145 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.369 ^-1.906 ^0.145 ~ ~