#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.369 ^-1.741 ^0.126 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.369 ^-1.818 ^0.139 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.369 ^-1.874 ^0.148 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.369 ^-1.935 ^0.158 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.369 ^-1.931 ^0.158 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.369 ^-1.899 ^0.152 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.369 ^-1.875 ^0.148 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.369 ^-1.874 ^0.148 ~ ~