#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.369 ^-1.855 ^0.212 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.369 ^-1.967 ^0.223 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.369 ^-2.096 ^0.236 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.369 ^-2.279 ^0.257 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.369 ^-2.477 ^0.28 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.369 ^-2.651 ^0.301 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.369 ^-2.75 ^0.313 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.369 ^-2.75 ^0.313 ~ ~