#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-63.1753f,-0.0499f,1.6457f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-24.5469f,0.5057f,-0.1128f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [6.7309f,1.8923f,-1.9519f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [27.0643f,3.3961f,-4.1869f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [33.4924f,6.3707f,-16.6056f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [27.7171f,8.2772f,-27.6878f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [28.3015f,7.0447f,-21.8585f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [29.57f,3.4013f,-4.3433f]