#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [55.3036f,-14.2063f,-6.0557f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [55.6197f,-13.978f,4.3783f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [56.0549f,-13.4347f,15.4324f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [56.784f,-12.6569f,25.4693f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [57.9814f,-11.7252f,32.8516f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [59.8951f,-10.6889f,35.9795f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [63.7163f,-9.2252f,34.2837f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [68.8809f,-7.4125f,28.8224f]