#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [108.8047f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [109.0276f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [109.2868f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [109.5839f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [109.9201f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [110.2971f,0f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [110.7161f,0f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [111.1787f,0f,0f]