#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [96.053f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [106.0207f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [113.27f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [121.1214f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [120.6198f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [116.4648f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [113.3563f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [113.2614f,0f,0f]