#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.1054f,0.1592f,0.2133f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.647f,0.4017f,0.5382f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.7225f,0.6594f,0.8835f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0.5706f,0.864f,1.1577f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [4.1344f,0.9474f,1.2694f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [11.2993f,1.0806f,1.448f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [21.4638f,1.3093f,1.7543f]