#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.369 ^-1.056 ^0.009 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.369 ^-1.133 ^0.023 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.369 ^-1.226 ^0.038 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.369 ^-1.329 ^0.056 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.369 ^-1.437 ^0.074 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.369 ^-1.546 ^0.092 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.369 ^-1.649 ^0.11 ~ ~