#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.832 ^-2.133 ^1.115 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.85 ^-2.035 ^1.131 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.852 ^-2.116 ^1.107 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.813 ^-2.3 ^1.064 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.787 ^-2.373 ^1.046 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.783 ^-2.384 ^1.043 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.785 ^-2.378 ^1.043 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.79 ^-2.362 ^1.044 ~ ~