#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.506 ^-3.087 ^0.298 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.485 ^-3.091 ^0.321 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.437 ^-3.104 ^0.359 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.382 ^-3.119 ^0.406 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.341 ^-3.13 ^0.457 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.328 ^-3.136 ^0.507 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.372 ^-3.13 ^0.568 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.498 ^-3.092 ^0.656 ~ ~