#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.494 ^0.998 ^0.03 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.485 ^0.91 ^0.059 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.476 ^0.803 ^0.11 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.469 ^0.683 ^0.205 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.468 ^0.547 ^0.366 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.469 ^0.384 ^0.623 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.471 ^0.168 ^0.944 ~ ~