#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [143.1534f,-2.4693f,11.4791f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [144.0624f,-4.1725f,19.5774f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [145.6688f,-3.2724f,15.3899f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [146.881f,-0.7828f,3.681f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [147.4712f,0.1293f,-0.7528f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [147.9263f,0.0291f,-1.1585f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [148.2914f,-0.2899f,-0.6672f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [148.3337f,-0.5162f,0.0376f]