#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.369 ^-1.429 ^0.189 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.369 ^-1.422 ^0.189 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.369 ^-1.438 ^0.188 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.369 ^-1.474 ^0.186 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.369 ^-1.524 ^0.186 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.369 ^-1.584 ^0.189 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.369 ^-1.66 ^0.195 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.369 ^-1.751 ^0.203 ~ ~