#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function warden:animations/animation.warden.dig/tree/right_ribcage_root_64-71
execute if score .this aj.frame matches 72..79 run function warden:animations/animation.warden.dig/tree/right_ribcage_root_72-79
execute if score .this aj.frame matches 80..87 run function warden:animations/animation.warden.dig/tree/right_ribcage_root_80-87
execute if score .this aj.frame matches 88..95 run function warden:animations/animation.warden.dig/tree/right_ribcage_root_88-95
execute if score .this aj.frame matches 96..101 run function warden:animations/animation.warden.dig/tree/right_ribcage_root_96-101