#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [108.1585f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [108.1422f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [108.1507f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [108.1856f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [108.2482f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [108.3399f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [108.4623f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [108.6168f,0f,0f]