#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.41 ^-4.144 ^0.554 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.464 ^-4.236 ^0.526 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.5 ^-4.3 ^0.506 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.5 ^-4.3 ^0.506 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.5 ^-4.3 ^0.506 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.5 ^-4.3 ^0.506 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.5 ^-4.3 ^0.506 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.5 ^-4.3 ^0.506 ~ ~