#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.445 ^-1.389 ^0.616 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.444 ^-1.532 ^0.645 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.437 ^-1.642 ^0.668 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.413 ^-1.765 ^0.708 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.37 ^-1.809 ^0.731 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.326 ^-1.799 ^0.744 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.308 ^-1.773 ^0.752 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.321 ^-1.753 ^0.759 ~ ~