#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [43.8742f,1.7585f,-0.3446f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [41.1798f,2.5501f,-1.2648f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [37.3861f,4.5263f,-3.5137f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [32.9868f,6.9915f,-6.2669f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [28.5667f,9.1189f,-8.6315f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [24.712f,10.0818f,-9.7209f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [21.6256f,8.2918f,-7.8286f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [19.4592f,1.7734f,-0.8402f]