#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.472 ^-2.087 ^0.315 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.482 ^-2.108 ^0.339 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.47 ^-2.221 ^0.328 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.439 ^-2.382 ^0.3 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.4 ^-2.558 ^0.273 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.373 ^-2.723 ^0.264 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.374 ^-2.867 ^0.277 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.388 ^-2.992 ^0.297 ~ ~