#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.472 ^-1.177 ^0.349 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.466 ^-1.112 ^0.301 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.456 ^-1.063 ^0.262 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.447 ^-1.032 ^0.239 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.439 ^-1.023 ^0.235 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.431 ^-1.056 ^0.276 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.428 ^-1.158 ^0.365 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.433 ^-1.313 ^0.45 ~ ~