#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.348 ^-1.715 ^0.764 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.375 ^-1.66 ^0.767 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.392 ^-1.596 ^0.769 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.398 ^-1.534 ^0.768 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.398 ^-1.484 ^0.764 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.403 ^-1.457 ^0.755 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.422 ^-1.467 ^0.738 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.447 ^-1.508 ^0.714 ~ ~