#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.733 ^-1.728 ^1.238 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.733 ^-1.735 ^1.24 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.776 ^-1.92 ^1.2 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.759 ^-2.199 ^1.135 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.662 ^-2.442 ^1.07 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.604 ^-2.54 ^1.036 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.667 ^-2.478 ^1.046 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.77 ^-2.315 ^1.08 ~ ~