#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [110.6325f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [110.4133f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [110.196f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [109.9821f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [109.7729f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [109.5699f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [109.3746f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [109.1884f,0f,0f]