#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.439 ^-2.063 ^0.201 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.433 ^-2.066 ^0.198 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.418 ^-2.081 ^0.19 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.398 ^-2.103 ^0.182 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.379 ^-2.124 ^0.178 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.371 ^-2.14 ^0.181 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.387 ^-2.144 ^0.203 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.435 ^-2.116 ^0.258 ~ ~