#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.236 ^-1.152 ^2.029 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.377 ^-1.311 ^2.036 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.465 ^-1.461 ^2.024 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.514 ^-1.549 ^2.002 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.558 ^-1.598 ^1.972 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.602 ^-1.623 ^1.934 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.654 ^-1.618 ^1.888 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.718 ^-1.572 ^1.834 ~ ~