#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-1.009 ^-1.122 ^0.833 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-1.029 ^-1.063 ^0.729 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-1.034 ^-0.99 ^0.622 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-1.027 ^-0.9 ^0.487 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-1.005 ^-0.809 ^0.33 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.97 ^-0.729 ^0.162 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.925 ^-0.668 ^-0.006 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.879 ^-0.628 ^-0.163 ~ ~