#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.786 ^0.181 ^0.189 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.689 ^0.241 ^-0.115 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.606 ^0.245 ^-0.361 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.544 ^0.221 ^-0.526 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.505 ^0.201 ^-0.595 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.464 ^0.242 ^-0.439 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.425 ^0.284 ^0.018 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.406 ^0.152 ^0.674 ~ ~