#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.464 ^-1.568 ^0.686 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.465 ^-1.634 ^0.659 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.45 ^-1.688 ^0.637 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.431 ^-1.718 ^0.627 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.407 ^-1.741 ^0.621 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.38 ^-1.759 ^0.617 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.355 ^-1.767 ^0.614 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.34 ^-1.761 ^0.613 ~ ~