#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0 ^-1.56 ^0 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0 ^-1.493 ^0 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0 ^-1.434 ^0 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0 ^-1.384 ^0 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0 ^-1.276 ^0 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0 ^-1.21 ^0 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0 ^-1.189 ^0 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0 ^-1.21 ^-0.003 ~ ~