#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0 ^-0.546 ^0.061 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0 ^-0.534 ^0.045 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0 ^-0.523 ^0.03 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0 ^-0.514 ^0.017 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0 ^-0.506 ^0.007 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0 ^-0.5 ^0 ~ ~