#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [0f,0f,10f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-0.0134f,0f,10.0094f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-0.1503f,0f,10.1052f]