#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-39.7455f,-0.0707f,0.0951f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-35.7486f,-0.1313f,-0.0143f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-31.6238f,-0.1974f,0.0603f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-27.357f,-0.2574f,0.3209f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-22.9337f,-0.2994f,0.7694f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-18.6747f,-0.3138f,1.3616f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-15.4061f,-0.3008f,1.8671f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-11.6656f,-0.2539f,2.3764f]