#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.15 ^-1.652 ^0.126 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.148 ^-1.662 ^0.128 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.146 ^-1.673 ^0.129 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.144 ^-1.686 ^0.132 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.141 ^-1.7 ^0.134 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.139 ^-1.715 ^0.136 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.136 ^-1.73 ^0.137 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.135 ^-1.746 ^0.136 ~ ~