#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.0031f,0f,-1.2677f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.0111f,0f,-2.8725f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.0219f,0f,-4.7621f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-0.0337f,0f,-6.8842f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-0.0444f,0f,-9.1863f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.0521f,0f,-11.6163f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-0.0548f,0f,-14.1217f]