#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.126 ^-1.862 ^0.092 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.118 ^-1.862 ^0.092 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.11 ^-1.851 ^0.094 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.101 ^-1.826 ^0.095 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.091 ^-1.793 ^0.097 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.08 ^-1.748 ^0.1 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.068 ^-1.688 ^0.104 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.056 ^-1.61 ^0.108 ~ ~