#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [85.2168f,1.3423f,1.1403f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [77.8077f,1.1368f,0.9775f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [70.1576f,0.9364f,0.8248f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [62.3688f,0.747f,0.6865f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [54.5435f,0.574f,0.5648f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [46.7841f,0.4219f,0.46f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [39.1928f,0.2939f,0.3708f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [31.8721f,0.1915f,0.2949f]