#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.013 ^-0.407 ^0.967 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.013 ^-0.419 ^0.975 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.012 ^-0.431 ^0.983 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.012 ^-0.442 ^0.99 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.012 ^-0.452 ^0.996 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.011 ^-0.46 ^1.001 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.011 ^-0.465 ^1.004 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.011 ^-0.466 ^1.005 ~ ~