#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-3.625 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.052 ^-3.651 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.122 ^-3.7 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.201 ^-3.769 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.28 ^-3.851 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.352 ^-3.939 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.411 ^-4.023 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.455 ^-4.093 ^0 ~ ~