#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.337 ^-2.854 ^-0.004 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.285 ^-2.592 ^-0.004 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.237 ^-2.361 ^-0.001 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.196 ^-2.169 ^0.004 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.164 ^-2.012 ^0.012 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.142 ^-1.889 ^0.023 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.127 ^-1.793 ^0.034 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.116 ^-1.719 ^0.045 ~ ~