#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.007 ^-0.34 ^0.784 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.01 ^-0.347 ^0.831 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.012 ^-0.356 ^0.875 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.013 ^-0.365 ^0.91 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.014 ^-0.373 ^0.933 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.014 ^-0.378 ^0.941 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.014 ^-0.385 ^0.949 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.013 ^-0.395 ^0.958 ~ ~