#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.134 ^-1.764 ^0.134 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.135 ^-1.783 ^0.129 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.135 ^-1.801 ^0.123 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.136 ^-1.819 ^0.117 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.136 ^-1.834 ^0.109 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.135 ^-1.847 ^0.102 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.134 ^-1.854 ^0.097 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.131 ^-1.86 ^0.094 ~ ~