#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [98.8589f,-6.1591f,3.1556f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [95.5327f,-5.2776f,3.3832f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [103.6197f,-5.3421f,4.0592f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [105.5699f,-5.9281f,5.0225f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [102.989f,-6.9465f,6.4561f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [104.1744f,-7.0399f,6.2201f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [108.5388f,-7.3553f,6.4928f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [113.0901f,-7.4115f,6.5818f]