#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [0.2834f,0f,0.5522f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [1.0781f,0f,0.9361f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [2.3006f,0f,1.1725f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [3.8673f,0f,1.2823f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [5.6948f,0f,1.2863f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [7.6996f,0f,1.2055f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [9.7982f,0f,1.0607f]