#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.378 ^-1.009 ^-0.015 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.378 ^-1.01 ^-0.016 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.378 ^-1.01 ^-0.016 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.377 ^-1.009 ^-0.015 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.377 ^-1.008 ^-0.014 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.375 ^-1.007 ^-0.012 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.374 ^-1.006 ^-0.01 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.373 ^-1.005 ^-0.007 ~ ~