#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.47 ^-1.034 ^1.424 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.469 ^-1.038 ^1.446 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.467 ^-1.039 ^1.468 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.466 ^-1.037 ^1.493 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.465 ^-1.031 ^1.518 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.464 ^-1.019 ^1.544 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.464 ^-1 ^1.57 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.465 ^-0.973 ^1.597 ~ ~