#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.794 ^-1.215 ^-0.249 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.778 ^-1.142 ^-0.208 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.76 ^-1.061 ^-0.162 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.742 ^-0.975 ^-0.114 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.723 ^-0.887 ^-0.063 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.704 ^-0.8 ^-0.012 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.685 ^-0.714 ^0.038 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.668 ^-0.633 ^0.085 ~ ~