#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.504 ^-0.965 ^0.871 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.498 ^-0.956 ^0.878 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.494 ^-0.948 ^0.88 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.492 ^-0.941 ^0.88 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.489 ^-0.944 ^0.885 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.494 ^-0.935 ^0.904 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.499 ^-0.901 ^0.944 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.494 ^-0.838 ^0.979 ~ ~