#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.576 ^-1.605 ^-0.062 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.589 ^-1.55 ^-0.062 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.603 ^-1.519 ^-0.062 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.619 ^-1.508 ^-0.062 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.637 ^-1.513 ^-0.062 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.655 ^-1.529 ^-0.062 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.673 ^-1.551 ^-0.062 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.691 ^-1.575 ^-0.062 ~ ~