#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.635 ^-1.188 ^-0.347 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.634 ^-1.174 ^-0.31 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.635 ^-1.163 ^-0.272 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.638 ^-1.155 ^-0.23 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.643 ^-1.15 ^-0.185 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.65 ^-1.148 ^-0.141 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.656 ^-1.148 ^-0.104 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.66 ^-1.146 ^-0.06 ~ ~