#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.531 ^-0.758 ^1.265 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.528 ^-0.753 ^1.29 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0.523 ^-0.697 ^1.293 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0.518 ^-0.653 ^1.277 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0.513 ^-0.677 ^1.269 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0.509 ^-0.744 ^1.263 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0.506 ^-0.808 ^1.273 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0.503 ^-0.849 ^1.284 ~ ~