#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.369 ^-3.032 ^0 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.369 ^-3.015 ^0 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.369 ^-2.987 ^0 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.371 ^-2.951 ^-0.004 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.375 ^-2.909 ^-0.01 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.379 ^-2.861 ^-0.018 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.383 ^-2.806 ^-0.025 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.386 ^-2.743 ^-0.03 ~ ~