#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.244 ^-1.579 ^0.227 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.211 ^-1.393 ^0.284 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.181 ^-1.22 ^0.338 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.154 ^-1.069 ^0.384 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.132 ^-0.946 ^0.419 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.112 ^-0.839 ^0.444 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.1 ^-0.809 ^0.415 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.11 ^-0.916 ^0.343 ~ ~