#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [-0.2344f,0f,0f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [-0.1428f,0f,0f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [-0.0684f,0f,0f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [-0.0183f,0f,0f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [0f,0f,0f]