#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [4.8769f,-5.1572f,0.8387f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [7.6094f,-4.9888f,0.5623f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [10.37f,-4.8069f,0.2894f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [12.9885f,-4.6202f,0.0246f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [15.2949f,-4.438f,-0.2281f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [17.1194f,-4.27f,-0.4654f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [18.2923f,-4.1264f,-0.6843f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [18.644f,-4.0174f,-0.8819f]