#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.662 ^-1.144 ^-0.007 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.66 ^-1.142 ^0.056 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.656 ^-1.135 ^0.125 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.652 ^-1.12 ^0.195 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.645 ^-1.103 ^0.269 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.635 ^-1.081 ^0.345 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.623 ^-1.053 ^0.421 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.61 ^-1.014 ^0.496 ~ ~