#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.688 ^-1.536 ^-0.587 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.715 ^-1.579 ^-0.573 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.739 ^-1.576 ^-0.565 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.698 ^-1.432 ^-0.571 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.676 ^-1.287 ^-0.518 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.689 ^-1.236 ^-0.477 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.679 ^-1.388 ^-0.568 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.675 ^-1.39 ^-0.564 ~ ~