#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.369 ^-3.01 ^0 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.369 ^-3.018 ^0 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.369 ^-3.027 ^0 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.369 ^-3.035 ^0 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.369 ^-3.042 ^0 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.369 ^-3.046 ^0 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.369 ^-3.046 ^0 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.369 ^-3.042 ^0 ~ ~