#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [-5.0351f,-4.6226f,3.1298f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [-4.8045f,-5.0412f,2.8988f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [-4.3332f,-5.3568f,2.5877f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [-3.5434f,-5.5288f,2.2264f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [-2.3595f,-5.5515f,1.8548f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [-1.4462f,-5.5069f,1.6282f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [0.1783f,-5.4227f,1.3784f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [2.343f,-5.3041f,1.1129f]