#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.435 ^-0.961 ^0.454 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.434 ^-0.944 ^0.455 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.432 ^-0.926 ^0.455 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.43 ^-0.91 ^0.454 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.429 ^-0.899 ^0.453 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.428 ^-0.897 ^0.453 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.428 ^-0.898 ^0.452 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.428 ^-0.9 ^0.452 ~ ~