#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-0.4f,0f,10.28f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-0.7192f,0f,10.5034f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-1.0644f,0f,10.745f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-1.3922f,0f,10.9745f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-1.6593f,0f,11.1615f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-1.8222f,0f,11.2755f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-1.8375f,0f,11.2863f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-1.6619f,0f,11.1633f]