#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.673 ^-1.375 ^-0.554 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.671 ^-1.356 ^-0.54 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.667 ^-1.334 ^-0.523 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.663 ^-1.31 ^-0.502 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.657 ^-1.284 ^-0.477 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.651 ^-1.256 ^-0.448 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.644 ^-1.23 ^-0.415 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.638 ^-1.207 ^-0.381 ~ ~