#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [29.2188f,0f,-7.9687f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [25.1492f,0f,-7.9642f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [25.4775f,0f,-7.2582f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [27.6672f,0f,-6.4006f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [30.9259f,0f,-5.2778f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [34.8115f,0f,-4.0103f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [38.882f,0f,-2.7186f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [42.6953f,0f,-1.5234f]