#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.737 ^-1.649 ^-0.069 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.732 ^-1.63 ^-0.065 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.73 ^-1.584 ^-0.083 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.742 ^-1.475 ^-0.17 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.756 ^-1.352 ^-0.263 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.766 ^-1.267 ^-0.314 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.786 ^-1.272 ^-0.322 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.803 ^-1.276 ^-0.29 ~ ~