#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.615 ^-1.999 ^0.068 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.614 ^-1.755 ^0.058 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.584 ^-1.53 ^0.028 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.506 ^-1.325 ^-0.061 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.317 ^-1.16 ^-0.237 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.055 ^-1.113 ^-0.427 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.177 ^-1.197 ^-0.57 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.308 ^-1.315 ^-0.639 ~ ~