#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.477 ^-0.786 ^0.972 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.462 ^-0.776 ^0.952 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.462 ^-0.878 ^0.953 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.475 ^-0.878 ^0.987 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.5 ^-0.806 ^1.052 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.516 ^-0.759 ^1.124 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0.527 ^-0.755 ^1.183 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0.531 ^-0.756 ^1.231 ~ ~