#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.813 ^-3.625 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.797 ^-3.783 ^-0.062 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.788 ^-3.976 ^-0.062 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.777 ^-3.995 ^-0.062 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.761 ^-3.952 ^-0.062 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.743 ^-3.899 ^-0.062 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.723 ^-3.834 ^-0.062 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.703 ^-3.76 ^-0.062 ~ ~