#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.369 ^-4.683 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.369 ^-4.616 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.369 ^-4.537 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.369 ^-4.454 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.369 ^-4.364 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.369 ^-4.258 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.369 ^-4.141 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.369 ^-4.015 ^0 ~ ~