#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^0.781 ^-0.104 ^0.793 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^0.786 ^-0.052 ^0.735 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0.79 ^0 ^0.671 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0.794 ^0.052 ^0.601 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0.798 ^0.101 ^0.526 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0.801 ^0.146 ^0.448 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0.803 ^0.186 ^0.368 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0.805 ^0.22 ^0.289 ~ ~