#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [-27.571f,-2.4996f,-6.8605f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [-30.4757f,-0.5921f,-7.8113f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [-29.3526f,0.0678f,-7.1846f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [-26.7686f,0.0157f,-5.921f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [-23.154f,-0.3327f,-4.1819f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [-18.9446f,-0.9377f,-2.2291f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [-14.5731f,-1.7204f,-0.3076f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [-10.4682f,-2.5566f,1.3804f]