#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.731 ^-1.625 ^-0.064 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.733 ^-1.634 ^-0.066 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.736 ^-1.644 ^-0.068 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.738 ^-1.653 ^-0.069 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.74 ^-1.661 ^-0.07 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.741 ^-1.666 ^-0.071 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.741 ^-1.666 ^-0.071 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.74 ^-1.661 ^-0.071 ~ ~