#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.716 ^-0.197 ^0.95 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.717 ^-0.214 ^0.961 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.72 ^-0.232 ^0.971 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.722 ^-0.249 ^0.98 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.725 ^-0.265 ^0.987 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.728 ^-0.279 ^0.992 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.732 ^-0.291 ^0.995 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.736 ^-0.299 ^0.995 ~ ~