#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.372 ^-1.003 ^-0.005 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.371 ^-1.002 ^-0.003 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.37 ^-1.001 ^-0.001 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.369 ^-1.001 ^0 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.369 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.369 ^-1 ^0 ~ ~