#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^0.432 ^-0.808 ^0.444 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^0.433 ^-0.775 ^0.438 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0.434 ^-0.739 ^0.43 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0.435 ^-0.701 ^0.42 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0.436 ^-0.661 ^0.407 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0.437 ^-0.62 ^0.392 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0.437 ^-0.58 ^0.375 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0.438 ^-0.541 ^0.356 ~ ~