#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.51 ^0.905 ^0.606 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.508 ^0.966 ^0.452 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.506 ^1.009 ^0.309 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.503 ^1.037 ^0.18 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.501 ^1.054 ^0.071 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.5 ^1.062 ^0 ~ ~