#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-91.7224f,-18.1084f,-1.1411f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-90.7749f,-17.7756f,-1.8906f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-88.9468f,-16.893f,-2.9363f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-85.007f,-14.6071f,-4.3104f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-80.6628f,-11.8482f,-5.8795f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-77.7474f,-9.2451f,-7.5207f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-78.4863f,-6.1381f,-10.3541f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-78.0131f,-3.8865f,-11.3143f]