#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-172.0918f,-17.5f,-8.8354f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-173.8377f,-17.5f,-3.9208f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-176.1129f,-17.5296f,-1.0664f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [179.082f,-17.793f,-0.2503f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [173.0612f,-18.156f,-0.7763f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [167.9173f,-18.4051f,-1.9602f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [165.743f,-18.3268f,-3.1178f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [168.6308f,-17.7076f,-3.5647f]