#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-1.066 ^-3.602 ^-0.024 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-1.075 ^-3.591 ^-0.034 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-1.069 ^-3.571 ^-0.052 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-1.049 ^-3.548 ^-0.077 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-1.02 ^-3.525 ^-0.11 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.982 ^-3.501 ^-0.151 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.94 ^-3.476 ^-0.2 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.895 ^-3.45 ^-0.254 ~ ~