#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [55.2783f,0f,0.8643f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [59.6282f,0f,1.3476f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [63.8751f,0f,1.8195f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [67.504f,0f,2.2227f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [70f,0f,2.5f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [70.7462f,0f,2.5732f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [71.5552f,0f,2.6367f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [72.3923f,0f,2.6904f]