#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.622 ^-1.868 ^-0.137 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.579 ^-1.756 ^-0.084 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.52 ^-1.613 ^-0.03 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.513 ^-1.564 ^-0.034 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.536 ^-1.581 ^-0.062 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.535 ^-1.576 ^-0.062 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.535 ^-1.573 ^-0.062 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.534 ^-1.572 ^-0.062 ~ ~