#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.774 ^-0.634 ^0.06 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.789 ^-0.569 ^0.11 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.802 ^-0.513 ^0.154 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.812 ^-0.469 ^0.19 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.831 ^-0.394 ^0.273 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.825 ^-0.342 ^0.339 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.812 ^-0.32 ^0.367 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.813 ^-0.335 ^0.342 ~ ~