#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [7.8813f,0f,4.1886f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [9.5145f,0f,2.9812f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [11.1947f,0f,1.747f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [12.8998f,0f,0.505f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [14.6079f,0f,-0.7255f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [16.2969f,0f,-1.9251f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [17.9448f,0f,-3.0747f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [19.5296f,0f,-4.1549f]