#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.822 ^-0.408 ^0.249 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.823 ^-0.47 ^0.18 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.808 ^-0.449 ^0.217 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.789 ^-0.398 ^0.301 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.763 ^-0.331 ^0.417 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.733 ^-0.262 ^0.549 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.703 ^-0.201 ^0.682 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.677 ^-0.155 ^0.799 ~ ~