#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.369 ^-3.032 ^0 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.369 ^-3.015 ^0 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.369 ^-2.986 ^0 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.369 ^-2.942 ^0.001 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.369 ^-2.888 ^0.004 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.369 ^-2.825 ^0.006 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.369 ^-2.755 ^0.009 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.369 ^-2.681 ^0.011 ~ ~