#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.534 ^-1.572 ^-0.062 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.535 ^-1.574 ^-0.062 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.535 ^-1.576 ^-0.062 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.535 ^-1.578 ^-0.062 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.536 ^-1.58 ^-0.062 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.536 ^-1.581 ^-0.062 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.536 ^-1.581 ^-0.063 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.534 ^-1.581 ^-0.065 ~ ~