#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.781 ^-0.004 ^0.845 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.782 ^0.043 ^0.779 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.784 ^0.089 ^0.707 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.786 ^0.133 ^0.629 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.789 ^0.174 ^0.547 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.792 ^0.21 ^0.463 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.795 ^0.241 ^0.379 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.798 ^0.265 ^0.296 ~ ~