#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [30.9375f,0f,0f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [50.7098f,0f,0f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [51.5625f,0f,0f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [24.5877f,0f,0f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [-2.6318f,0f,0f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [-3.8672f,0f,0f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [-4.0283f,0f,0f]