#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [56.6591f,0f,2.0235f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [52.1281f,0f,1.8617f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [47.2959f,0f,1.6891f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [42.2512f,0f,1.509f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [37.0824f,0f,1.3244f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [31.8782f,0f,1.1385f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [26.7271f,0f,0.9545f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [21.7178f,0f,0.7756f]