#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.405 ^-2.306 ^0.247 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.407 ^-2.303 ^0.249 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.41 ^-2.293 ^0.251 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.413 ^-2.268 ^0.253 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.416 ^-2.237 ^0.255 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.42 ^-2.196 ^0.257 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.423 ^-2.142 ^0.26 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.427 ^-2.071 ^0.262 ~ ~