#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.447 ^-0.861 ^0.452 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.447 ^-0.865 ^0.452 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.447 ^-0.869 ^0.452 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.447 ^-0.874 ^0.452 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.447 ^-0.878 ^0.452 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.447 ^-0.882 ^0.452 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.447 ^-0.885 ^0.452 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.447 ^-0.886 ^0.453 ~ ~