#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-58.1635f,0.4773f,-15.3191f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-71.7804f,0.598f,-13.1099f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-85.5378f,0.7445f,-10.8238f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-99.1048f,0.9228f,-8.5413f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-112.1504f,1.1388f,-6.3429f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-124.3437f,1.3986f,-4.309f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-135.3537f,1.7081f,-2.5203f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-144.8494f,2.0732f,-1.0571f]