#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.439 ^-0.947 ^0.454 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.441 ^-0.924 ^0.455 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.443 ^-0.899 ^0.455 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.444 ^-0.876 ^0.454 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.445 ^-0.861 ^0.453 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.446 ^-0.858 ^0.453 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.446 ^-0.858 ^0.452 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.446 ^-0.859 ^0.452 ~ ~