#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.528 ^-1.002 ^1.374 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.529 ^-1.004 ^1.394 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.531 ^-1.005 ^1.417 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.532 ^-1.002 ^1.441 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.533 ^-0.995 ^1.466 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.534 ^-0.983 ^1.493 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.534 ^-0.964 ^1.52 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.533 ^-0.937 ^1.548 ~ ~