#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,0f,8.0671f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,0f,9.3823f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,0f,11.0127f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0f,0f,10.8861f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0f,0f,10f]