#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-0.0458f,0f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-0.219f,0f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-0.4996f,0f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [-0.864f,0f,0f]