#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.369 ^-1.98 ^-0.097 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.369 ^-1.904 ^-0.119 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.369 ^-1.836 ^-0.139 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.369 ^-1.778 ^-0.153 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.369 ^-1.683 ^-0.166 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.369 ^-1.614 ^-0.163 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.369 ^-1.583 ^-0.156 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.369 ^-1.602 ^-0.154 ~ ~