#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^-0.49 ^0.909 ^0.604 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^-0.492 ^0.969 ^0.451 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^-0.494 ^1.011 ^0.308 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^-0.497 ^1.039 ^0.18 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^-0.499 ^1.055 ^0.071 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^-0.5 ^1.062 ^0 ~ ~