#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [-9.8527f,1.7423f,1.2478f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [-6.5209f,1.6632f,2.1294f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [-8.098f,1.6429f,2.3534f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [-12.279f,1.6864f,1.8697f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [-11.73f,1.7788f,1.7938f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [-9.3047f,1.8612f,1.747f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [-7f,1.6043f,1.888f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [-5.7587f,1.3342f,2.0146f]