#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.369 ^-3 ^0 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.369 ^-2.938 ^0 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.369 ^-2.903 ^0 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.369 ^-2.89 ^0 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.369 ^-2.894 ^0 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.369 ^-2.911 ^0 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.369 ^-2.935 ^0 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.369 ^-2.96 ^0 ~ ~