#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.25 ^-1.189 ^-0.587 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.198 ^-1.172 ^-0.573 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.181 ^-1.183 ^-0.565 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.293 ^-1.298 ^-0.571 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.322 ^-1.221 ^-0.518 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.307 ^-1.148 ^-0.477 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.317 ^-1.295 ^-0.568 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.322 ^-1.305 ^-0.564 ~ ~