#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.812 ^-3.625 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.833 ^-3.62 ^-0.06 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.861 ^-3.616 ^-0.054 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.896 ^-3.613 ^-0.046 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.935 ^-3.611 ^-0.037 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.975 ^-3.61 ^-0.029 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-1.013 ^-3.61 ^-0.023 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-1.044 ^-3.608 ^-0.021 ~ ~