#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [176.3368f,11.3252f,0.2604f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [178.2626f,12.1359f,0.0412f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-170.7581f,13.0787f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-127.0696f,13.0064f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-90f,12.5f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-86.2382f,12.5f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-84.1243f,12.5f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-83.3533f,12.5f,0f]