#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.369 ^-2.606 ^0.011 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.369 ^-2.53 ^0.011 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.369 ^-2.457 ^0.007 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.369 ^-2.388 ^0.002 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.369 ^-2.312 ^-0.01 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.369 ^-2.229 ^-0.027 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.369 ^-2.145 ^-0.049 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.369 ^-2.061 ^-0.073 ~ ~