#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [45.8093f,0f,-0.5453f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [48.2878f,0f,0.2626f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [48.9063f,0f,0.4688f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [47.5716f,0f,0.0239f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [46.6667f,0f,-0.0926f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [45.918f,0f,-0.1758f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [48.3295f,0f,0.0922f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [51.3404f,0f,0.4267f]