#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.437 ^-4.313 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.44 ^-4.304 ^0.25 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.444 ^-4.299 ^0.25 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.448 ^-4.296 ^0.25 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.451 ^-4.293 ^0.25 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.454 ^-4.285 ^0.25 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.455 ^-4.271 ^0.25 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.455 ^-4.247 ^0.25 ~ ~