#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-1.2891f,0f,0f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [-1.7514f,0f,0f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [-2.2278f,0f,0f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [-2.6948f,0f,0f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [-3.1292f,0f,0f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [-3.5076f,0f,0f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [-3.8068f,0f,0f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [-4.0034f,0f,0f]