#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-73.015f,0f,-7.6325f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-65.6836f,0f,-8.1965f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-50.1562f,0f,-6.2167f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-52.9492f,0f,-4.8975f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-67.5f,0f,-1.9994f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-68.7049f,0f,2.6643f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-68.9759f,0f,8.6054f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-68.6548f,0f,14.8164f]