#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-51.1435f,1.6944f,3.1493f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [-47.9035f,1.8087f,-0.5813f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [-45.0934f,2.0175f,-3.7655f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [-42.8491f,2.2313f,-6.1031f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [-37.9397f,2.383f,-8.3652f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [-34.1048f,2.4846f,-8.3518f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [-32.4703f,2.4597f,-7.3838f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [-33.856f,2.3497f,-7.0604f]