#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.431 ^-1.375 ^0.267 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.434 ^-1.431 ^0.268 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.435 ^-1.414 ^0.286 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.434 ^-1.37 ^0.307 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.434 ^-1.307 ^0.334 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.434 ^-1.233 ^0.364 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.434 ^-1.155 ^0.393 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.435 ^-1.079 ^0.418 ~ ~