#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.521 ^-1.584 ^-0.08 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.529 ^-1.582 ^-0.071 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.541 ^-1.58 ^-0.057 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.558 ^-1.594 ^-0.037 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.576 ^-1.608 ^-0.017 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.593 ^-1.592 ^-0.008 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.603 ^-1.51 ^-0.022 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.608 ^-1.326 ^-0.071 ~ ~