#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.77 ^-0.186 ^1.11 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.772 ^-0.186 ^1.096 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.774 ^-0.18 ^1.079 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.775 ^-0.168 ^1.057 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.776 ^-0.149 ^1.03 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.777 ^-0.123 ^0.996 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.778 ^-0.089 ^0.954 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.779 ^-0.048 ^0.904 ~ ~