#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.631 ^-1.512 ^-0.663 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.623 ^-1.364 ^-0.621 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.604 ^-1.138 ^-0.515 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.561 ^-1.142 ^-0.542 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.502 ^-1.283 ^-0.634 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.448 ^-1.27 ^-0.631 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.386 ^-1.244 ^-0.619 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.317 ^-1.214 ^-0.603 ~ ~