#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#warden:bone_entities,tag=aj.warden.bone,distance=..4.018] if score @s aj.id = .this aj.id run function warden:animations/animation.warden.sonic_boom/tree/trunk
scoreboard players operation @s aj.frame += .aj.warden.framerate aj.i
scoreboard players set .aj.animation aj.warden.animating 1
execute unless score @s aj.frame matches 0..62 run function warden:animations/animation.warden.sonic_boom/edge