#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-34.3042f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-32.789f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-28.584f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-21.5844f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-13.5459f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-6.0285f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-0.592f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [2.2856f,0f,0f]