#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [56.0067f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [52.4496f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [44.7405f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [34.6241f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [23.3845f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [12.3061f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [2.6729f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-16.1713f,0f,0f]