#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.643 ^-0.004 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-0.652 ^-0.004 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-0.661 ^-0.004 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-0.67 ^-0.003 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.677 ^-0.002 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-0.684 ^-0.001 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-0.692 ^0.001 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-0.704 ^0.006 ~ ~