#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-0.754 ^0.062 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-0.739 ^0.061 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-0.702 ^0.054 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-0.652 ^0.041 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-0.598 ^0.027 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-0.547 ^0.013 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-0.509 ^0.002 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-0.496 ^-0.001 ~ ~