#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.312 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.307 ^0.02 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.3 ^0.044 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.291 ^0.072 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^0.281 ^0.102 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^0.267 ^0.136 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^0.252 ^0.171 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.233 ^0.209 ~ ~