#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [93.1709f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [98.7677f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [103.9074f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [108.5182f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [112.5283f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [116.8113f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [121.3191f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [126.4524f,0f,0f]