#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [52.9058f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [54.8062f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [56.3806f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [57.5757f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [58.3387f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [58.6164f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [58.3556f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [57.5034f,0.0358f,0.0562f]