#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [45.2312f,0.7191f,-21.8147f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [44.4668f,0.0189f,-21.3404f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [43.7477f,-0.4688f,-21.0374f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [43.1202f,-0.768f,-20.8991f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [42.6279f,-0.8951f,-20.9136f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [42.3127f,-0.86f,-21.0643f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [42.2142f,-0.6669f,-21.3312f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [42.3709f,-0.3157f,-21.6906f]