#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.5 ^0.782 ^0.735 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.5 ^0.698 ^0.837 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.5 ^0.603 ^0.933 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.5 ^0.499 ^1.02 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.5 ^0.387 ^1.097 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.5 ^0.272 ^1.163 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.5 ^0.154 ^1.216 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.5 ^0.036 ^1.259 ~ ~