#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [50.1011f,19.1669f,-24.4097f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [35.505f,13.8463f,-18.5383f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [21.1396f,8.3206f,-11.258f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [8.5987f,3.3364f,-4.5187f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0f,0f,0f]