#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [15.77f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [18.3772f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [21.0397f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [23.7318f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [26.4275f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [29.1011f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [31.7267f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [34.2786f,0f,0f]