#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.611 ^0.162 ^-0.492 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.608 ^0.152 ^-0.511 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.606 ^0.144 ^-0.524 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.604 ^0.138 ^-0.534 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.603 ^0.134 ^-0.538 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.602 ^0.133 ^-0.538 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.602 ^0.135 ^-0.534 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.602 ^0.139 ^-0.525 ~ ~