#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0.0862f,1.068f,0.1872f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0.0997f,2.4019f,0.3889f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0.0656f,3.9638f,0.6564f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0.0119f,5.712f,1.0404f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-0.031f,7.6001f,1.5888f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.0302f,9.5764f,2.3449f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0.0477f,11.5841f,3.3444f]