#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0.2349f,13.5623f,4.614f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0.5596f,15.4471f,6.1683f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [1.0434f,17.1738f,8.0076f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [1.698f,18.6796f,10.116f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [2.5234f,19.9069f,12.4597f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [3.5072f,20.8062f,14.9879f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [4.6263f,21.3392f,17.6344f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [5.8503f,21.4804f,20.3228f]