#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.5 ^0.409 ^-1.044 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.5 ^0.447 ^-1.018 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.5 ^0.521 ^-0.945 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.5 ^0.616 ^-0.815 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.5 ^0.699 ^-0.655 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.5 ^0.767 ^-0.495 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.5 ^0.831 ^-0.361 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.5 ^0.93 ^-0.233 ~ ~