#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.5 ^-0.078 ^1.29 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.5 ^-0.187 ^1.312 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.5 ^-0.288 ^1.325 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.5 ^-0.379 ^1.332 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.5 ^-0.46 ^1.335 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.5 ^-0.54 ^1.331 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.5 ^-0.625 ^1.323 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.5 ^-0.726 ^1.312 ~ ~