#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-80.8262f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-78.2088f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-73.584f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-67.5697f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-61.2421f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-54.2941f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-46.4186f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-33.5666f,0f,0f]