#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [1.5563f,6.375f,35.61f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [1.1075f,12.807f,31.2584f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [9.2986f,23.7665f,22.341f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [29.2832f,35.7552f,6.2354f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [45.8583f,40.5743f,-14.6139f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [58.7327f,33.9062f,-29.3512f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [71.8637f,16.6299f,-21.6087f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [59.3476f,7.0572f,-21.4387f]