#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.653 ^0.314 ^-0.037 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.695 ^0.312 ^-0.058 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.742 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.784 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~