#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-18.2484f,-8.1942f,-34.8604f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-19.1832f,-14.3855f,-30.5916f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-8.5402f,-24.9175f,-21.7312f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [18.372f,-36.3441f,-5.7368f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [42.5142f,-40.719f,14.8382f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [60.0878f,-33.8596f,29.232f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [72.2005f,-16.6224f,21.5788f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [59.3476f,-7.0572f,21.4387f]