#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.5 ^-1.037 ^1.278 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.5 ^-0.937 ^1.31 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.5 ^-0.709 ^1.34 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.5 ^-0.397 ^1.331 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.5 ^0.307 ^1.228 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.5 ^0.932 ^0.559 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.5 ^0.914 ^-0.196 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.5 ^0.663 ^-0.719 ~ ~