#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.683 ^-0.176 ^0.622 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.677 ^-0.207 ^0.647 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.671 ^-0.235 ^0.668 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.666 ^-0.258 ^0.687 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.66 ^-0.273 ^0.701 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.655 ^-0.281 ^0.71 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.65 ^-0.28 ^0.714 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.646 ^-0.27 ^0.711 ~ ~