#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.5 ^0.379 ^-1.019 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.5 ^0.331 ^-1.042 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.5 ^0.303 ^-1.059 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.5 ^0.292 ^-1.071 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.5 ^0.296 ^-1.077 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.5 ^0.313 ^-1.079 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.5 ^0.339 ^-1.075 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.5 ^0.372 ^-1.063 ~ ~