#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.1907f,-1.0816f,-0.1281f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.5181f,-2.435f,-0.2604f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.9495f,-4.0237f,-0.4497f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-1.4492f,-5.8074f,-0.7488f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-1.9783f,-7.7408f,-1.2075f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-2.4959f,-9.7731f,-1.8714f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-2.9598f,-11.8481f,-2.7788f]