#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.5 ^-0.818 ^1.298 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.5 ^-0.9 ^1.281 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.5 ^-0.969 ^1.265 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.5 ^-1.024 ^1.252 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.5 ^-1.063 ^1.242 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.5 ^-1.086 ^1.239 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.5 ^-1.091 ^1.244 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.5 ^-1.076 ^1.257 ~ ~