#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.sniff/tree/body_root_0-63
execute if score .this aj.frame matches 64 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0 ^-0.5 ^0 ~ ~