#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.sniff/tree/head_root_0-63
execute if score .this aj.frame matches 64 run tp @s ^0.003 ^0.312 ^0.026 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.001 ^0.312 ^0.013 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0 ^0.312 ^0.003 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0 ^0.312 ^0 ~ ~