#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-0.1007f,50.1994f,0.208f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0.5203f,46.7437f,0.3245f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-3.6608f,44.5411f,0.4622f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-11.0566f,43.1396f,0.6331f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-19.4944f,42.2037f,0.8432f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-26.8103f,41.3982f,1.0855f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-30.8508f,40.3882f,1.3355f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-29.3959f,39.2393f,1.5891f]