#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.012 ^0.303 ^0.122 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.009 ^0.302 ^0.128 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.006 ^0.301 ^0.133 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.003 ^0.3 ^0.138 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^0.3 ^0.141 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.007 ^0.299 ^0.146 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.015 ^0.298 ^0.15 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.024 ^0.297 ^0.152 ~ ~