#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [12.4666f,7.5605f,0.3233f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [12.69f,1.4306f,-0.4144f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [12.693f,-4.5449f,-1.1956f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [12.4936f,-10.1592f,-1.9878f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [12.0942f,-15.2072f,-2.7473f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [11.8131f,-21.0193f,-3.5231f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [10.9558f,-26.6769f,-4.3148f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [8.0239f,-31.962f,-5.0878f]