#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.679 ^0.302 ^0.469 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.643 ^0.298 ^0.523 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.612 ^0.295 ^0.563 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.589 ^0.293 ^0.589 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.574 ^0.295 ^0.602 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.573 ^0.299 ^0.597 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.585 ^0.306 ^0.577 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.607 ^0.311 ^0.546 ~ ~