#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.284 ^-0.442 ^0.431 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.26 ^-0.449 ^0.447 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.239 ^-0.454 ^0.458 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.223 ^-0.456 ^0.467 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.209 ^-0.454 ^0.473 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.198 ^-0.446 ^0.477 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.193 ^-0.434 ^0.478 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.192 ^-0.42 ^0.476 ~ ~