#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.485 ^-0.426 ^0.169 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.494 ^-0.427 ^0.141 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.501 ^-0.427 ^0.113 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.506 ^-0.427 ^0.087 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.51 ^-0.426 ^0.063 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.512 ^-0.425 ^0.043 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.513 ^-0.424 ^0.028 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.513 ^-0.423 ^0.017 ~ ~