#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [5.7659f,5.4547f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [6.9565f,4.0236f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [8.0676f,2.6329f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [9.0863f,1.2894f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [10f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [11.9789f,-2.7785f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [14.1272f,-5.8391f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [16.3648f,-9.082f,0f]