#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.339 ^-0.394 ^0.378 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.349 ^-0.397 ^0.37 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.358 ^-0.399 ^0.362 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.368 ^-0.402 ^0.353 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.377 ^-0.405 ^0.344 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.386 ^-0.407 ^0.335 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.394 ^-0.41 ^0.326 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.402 ^-0.412 ^0.316 ~ ~