#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.813 ^0.312 ^-0.062 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.814 ^0.313 ^-0.022 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.812 ^0.314 ^0.034 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.806 ^0.314 ^0.102 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.794 ^0.314 ^0.177 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.774 ^0.312 ^0.255 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.747 ^0.309 ^0.332 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.714 ^0.306 ^0.405 ~ ~