#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.803 ^0.312 ^0.137 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.806 ^0.312 ^0.123 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.808 ^0.311 ^0.109 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.811 ^0.311 ^0.094 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.813 ^0.311 ^0.08 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.816 ^0.31 ^0.045 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.817 ^0.309 ^0.006 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.817 ^0.309 ^-0.037 ~ ~