#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.112 ^1.01 ^0.614 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.237 ^1.017 ^0.534 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.346 ^1.012 ^0.458 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.416 ^1.005 ^0.399 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.427 ^1.012 ^0.375 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.404 ^1.031 ^0.364 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.367 ^1.05 ^0.366 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.334 ^1.059 ^0.378 ~ ~