#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [18.6116f,-12.4074f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [20.7875f,-15.7154f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [22.8124f,-18.9062f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [24.6064f,-21.8801f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [26.0892f,-24.537f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [27.1809f,-26.7773f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [27.8014f,-28.5012f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [27.8705f,-29.6087f,0f]