#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [27.2864f,-30f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [25.8684f,-29.3466f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [23.7306f,-27.5464f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [21.0385f,-24.8394f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [17.9576f,-21.4656f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [14.6531f,-17.6652f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [11.2907f,-13.678f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [8.0357f,-9.7442f,0f]