#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.743 ^0.311 ^-0.337 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.743 ^0.311 ^-0.336 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.748 ^0.312 ^-0.323 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.756 ^0.313 ^-0.301 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.767 ^0.314 ^-0.27 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.778 ^0.314 ^-0.235 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.788 ^0.314 ^-0.197 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.797 ^0.314 ^-0.159 ~ ~