#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-13.667f,28.2174f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-12.9426f,27.0775f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-12.0933f,25.8677f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-11.1317f,24.595f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-10.0707f,23.2663f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-8.9229f,21.8883f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-7.7013f,20.4681f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-6.4186f,19.0125f,0f]