#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.773 ^0.309 ^0.268 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.756 ^0.309 ^0.313 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.737 ^0.309 ^0.355 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.718 ^0.309 ^0.393 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.7 ^0.309 ^0.424 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.684 ^0.309 ^0.449 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.671 ^0.309 ^0.466 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.664 ^0.31 ^0.475 ~ ~