#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^1.062 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.5 ^1.062 ^-0.002 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.5 ^1.062 ^-0.001 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.501 ^1.062 ^0.001 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.503 ^1.061 ^0.004 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.506 ^1.06 ^0.006 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.509 ^1.059 ^0.006 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.511 ^1.058 ^0.004 ~ ~