#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.319 ^1.063 ^-0.381 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.348 ^1.064 ^-0.351 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.323 ^1.063 ^-0.372 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.267 ^1.051 ^-0.428 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.203 ^1.021 ^-0.496 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.152 ^0.983 ^-0.552 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.131 ^0.958 ^-0.577 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.153 ^0.968 ^-0.554 ~ ~