#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.sniff/tree/right_tendril_root_0-63
execute if score .this aj.frame matches 64 run tp @s ^-0.485 ^1.06 ^0.15 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.496 ^1.061 ^0.074 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.5 ^1.062 ^0.016 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.5 ^1.062 ^0 ~ ~