#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.504 ^-0.377 ^0.014 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.504 ^-0.378 ^0.025 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.504 ^-0.38 ^0.036 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.503 ^-0.382 ^0.048 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.502 ^-0.384 ^0.061 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.501 ^-0.386 ^0.074 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.499 ^-0.389 ^0.087 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.497 ^-0.391 ^0.101 ~ ~