#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [14.5656f,17.5284f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [14.2522f,16.0226f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [13.9266f,14.5021f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [13.5888f,12.9737f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [13.2388f,11.4443f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [12.8766f,9.9208f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [12.5023f,8.4102f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [12.1157f,6.9191f,0f]