#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [3.7502f,-36.2215f,-5.6528f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-1.0482f,-39.6882f,-6.0265f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-5.522f,-42.5911f,-6.253f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-8.788f,-45.1551f,-6.4056f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-9.9299f,-47.6029f,-6.5837f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-7.9904f,-49.8482f,-6.7796f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-3.5519f,-51.492f,-6.8409f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [2.0117f,-52.2858f,-6.6659f]