#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.508 ^-0.406 ^-0.048 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.506 ^-0.392 ^-0.046 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.504 ^-0.382 ^-0.04 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.503 ^-0.376 ^-0.027 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.503 ^-0.375 ^-0.019 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.504 ^-0.375 ^-0.013 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.504 ^-0.375 ^-0.005 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.504 ^-0.376 ^0.004 ~ ~