#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.524 ^1.038 ^0.216 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.518 ^1.03 ^0.28 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.507 ^1.022 ^0.337 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.492 ^1.016 ^0.386 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.476 ^1.011 ^0.424 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.449 ^1.006 ^0.469 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.422 ^1.003 ^0.502 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.409 ^1.004 ^0.506 ~ ~