#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [23.1062f,36.4f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [20.7496f,35.7398f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [18.805f,34.5719f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [17.6167f,32.8961f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [17.3751f,31.9413f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [17.2081f,31.1495f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [17.0288f,30.2603f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [16.8374f,29.2806f,0f]