#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function warden:animations/animation.warden.sniff/tree/right_arm_root_0-63
execute if score .this aj.frame matches 64 run tp @s ^-0.812 ^0.314 ^0.05 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.814 ^0.313 ^-0.007 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.813 ^0.312 ^-0.05 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.812 ^0.312 ^-0.062 ~ ~