#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.815 ^0.312 ^-0.017 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.815 ^0.312 ^0.009 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.815 ^0.311 ^0.034 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.814 ^0.311 ^0.058 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.812 ^0.311 ^0.08 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.807 ^0.31 ^0.124 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.799 ^0.309 ^0.172 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.788 ^0.309 ^0.22 ~ ~