#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [8.6544f,5.4547f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [9.0808f,4.0236f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [9.4521f,2.6329f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [9.761f,1.2894f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [10f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [10.3819f,-2.7785f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [10.6944f,-5.8391f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [10.9375f,-9.082f,0f]