#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.673 ^0.314 ^-0.456 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.654 ^0.314 ^-0.482 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.645 ^0.313 ^-0.495 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.649 ^0.312 ^-0.492 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.656 ^0.312 ^-0.484 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.662 ^0.312 ^-0.475 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.67 ^0.312 ^-0.464 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.679 ^0.312 ^-0.45 ~ ~