#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [11.717f,5.4547f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [11.306f,4.0236f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [10.8829f,2.6329f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [10.4475f,1.2894f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [10f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [8.8412f,-2.7785f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [7.4724f,-5.8391f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [5.9522f,-9.082f,0f]