#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.06 ^1.091 ^-0.368 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.047 ^1.063 ^-0.447 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.115 ^1.029 ^-0.514 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.128 ^1.006 ^-0.559 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.084 ^1.011 ^-0.564 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.011 ^1.03 ^-0.546 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.129 ^1.049 ^-0.503 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.24 ^1.06 ^-0.441 ~ ~